// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Discovery.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Enum, determining the type of primitive value. All the primitive values are
// always stored in string value holder, but are interpreted differently
type CustomAccountDefEntry_PrimitiveValue int32

const (
	// Value should be interpreted as string
	CustomAccountDefEntry_STRING CustomAccountDefEntry_PrimitiveValue = 1
	// Value should be interpreted as numeric
	CustomAccountDefEntry_NUMERIC CustomAccountDefEntry_PrimitiveValue = 2
	// Value should be interpreted as boolean
	CustomAccountDefEntry_BOOLEAN CustomAccountDefEntry_PrimitiveValue = 3
)

var CustomAccountDefEntry_PrimitiveValue_name = map[int32]string{
	1: "STRING",
	2: "NUMERIC",
	3: "BOOLEAN",
}
var CustomAccountDefEntry_PrimitiveValue_value = map[string]int32{
	"STRING":  1,
	"NUMERIC": 2,
	"BOOLEAN": 3,
}

func (x CustomAccountDefEntry_PrimitiveValue) Enum() *CustomAccountDefEntry_PrimitiveValue {
	p := new(CustomAccountDefEntry_PrimitiveValue)
	*p = x
	return p
}
func (x CustomAccountDefEntry_PrimitiveValue) String() string {
	return proto1.EnumName(CustomAccountDefEntry_PrimitiveValue_name, int32(x))
}
func (x *CustomAccountDefEntry_PrimitiveValue) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(CustomAccountDefEntry_PrimitiveValue_value, data, "CustomAccountDefEntry_PrimitiveValue")
	if err != nil {
		return err
	}
	*x = CustomAccountDefEntry_PrimitiveValue(value)
	return nil
}
func (CustomAccountDefEntry_PrimitiveValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 0}
}

type ErrorDTO_ErrorSeverity int32

const (
	ErrorDTO_CRITICAL ErrorDTO_ErrorSeverity = 0
	ErrorDTO_WARNING  ErrorDTO_ErrorSeverity = 1
)

var ErrorDTO_ErrorSeverity_name = map[int32]string{
	0: "CRITICAL",
	1: "WARNING",
}
var ErrorDTO_ErrorSeverity_value = map[string]int32{
	"CRITICAL": 0,
	"WARNING":  1,
}

func (x ErrorDTO_ErrorSeverity) Enum() *ErrorDTO_ErrorSeverity {
	p := new(ErrorDTO_ErrorSeverity)
	*p = x
	return p
}
func (x ErrorDTO_ErrorSeverity) String() string {
	return proto1.EnumName(ErrorDTO_ErrorSeverity_name, int32(x))
}
func (x *ErrorDTO_ErrorSeverity) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(ErrorDTO_ErrorSeverity_value, data, "ErrorDTO_ErrorSeverity")
	if err != nil {
		return err
	}
	*x = ErrorDTO_ErrorSeverity(value)
	return nil
}
func (ErrorDTO_ErrorSeverity) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

// Type of the serialized data
type CustomMetadataDTO_Type int32

const (
	CustomMetadataDTO_JSON CustomMetadataDTO_Type = 0
	CustomMetadataDTO_XML  CustomMetadataDTO_Type = 1
)

var CustomMetadataDTO_Type_name = map[int32]string{
	0: "JSON",
	1: "XML",
}
var CustomMetadataDTO_Type_value = map[string]int32{
	"JSON": 0,
	"XML":  1,
}

func (x CustomMetadataDTO_Type) Enum() *CustomMetadataDTO_Type {
	p := new(CustomMetadataDTO_Type)
	*p = x
	return p
}
func (x CustomMetadataDTO_Type) String() string {
	return proto1.EnumName(CustomMetadataDTO_Type_name, int32(x))
}
func (x *CustomMetadataDTO_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(CustomMetadataDTO_Type_value, data, "CustomMetadataDTO_Type")
	if err != nil {
		return err
	}
	*x = CustomMetadataDTO_Type(value)
	return nil
}
func (CustomMetadataDTO_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{5, 0} }

// ValidateResponse is the response of a ValidateRequest message.
// It contains the response, and any errors encountered during the target validation attempt.
type ValidationResponse struct {
	// Errors, discovered during external probe operation
	ErrorDTO         []*ErrorDTO `protobuf:"bytes,1,rep,name=errorDTO" json:"errorDTO,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ValidationResponse) Reset()                    { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string            { return proto1.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()               {}
func (*ValidationResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ValidationResponse) GetErrorDTO() []*ErrorDTO {
	if m != nil {
		return m.ErrorDTO
	}
	return nil
}

// Mediation container response for target discovery request. Holds both errors and discovered
// entities. If errors occurred, any entities can be sent nevertheless. Only those entities should
// be updated in the operations manager.
//
// Errors do not prevent anything. They are just displayed to users in the UI
type DiscoveryResponse struct {
	// Errors, discovered during external probe operation
	ErrorDTO []*ErrorDTO `protobuf:"bytes,1,rep,name=errorDTO" json:"errorDTO,omitempty"`
	// Entities, discovered by external probe.
	EntityDTO []*EntityDTO `protobuf:"bytes,2,rep,name=entityDTO" json:"entityDTO,omitempty"`
	// Constraints defined in external probe
	DiscoveredGroup []*GroupDTO `protobuf:"bytes,3,rep,name=discoveredGroup" json:"discoveredGroup,omitempty"`
	// ServiceEntityProfile (template)
	EntityProfile []*EntityProfileDTO `protobuf:"bytes,4,rep,name=entityProfile" json:"entityProfile,omitempty"`
	// Deployment Profile (ServiceCatalogItem)
	DeploymentProfile []*DeploymentProfileDTO `protobuf:"bytes,5,rep,name=deploymentProfile" json:"deploymentProfile,omitempty"`
	// Notifications for global (not entity-specific) events
	Notification []*NotificationDTO `protobuf:"bytes,6,rep,name=notification" json:"notification,omitempty"`
	// Custom Metadata DTO
	MetadataDTO []*CustomMetadataDTO `protobuf:"bytes,7,rep,name=metadataDTO" json:"metadataDTO,omitempty"`
	// Derived targets' creation requests
	DerivedTarget []*DerivedTargetSpecificationDTO `protobuf:"bytes,8,rep,name=derivedTarget" json:"derivedTarget,omitempty"`
	// Non market entities, discovered by external probe
	NonMarketEntityDTO []*NonMarketEntityDTO `protobuf:"bytes,9,rep,name=nonMarketEntityDTO" json:"nonMarketEntityDTO,omitempty"`
	XXX_unrecognized   []byte                `json:"-"`
}

func (m *DiscoveryResponse) Reset()                    { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string            { return proto1.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()               {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DiscoveryResponse) GetErrorDTO() []*ErrorDTO {
	if m != nil {
		return m.ErrorDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetEntityDTO() []*EntityDTO {
	if m != nil {
		return m.EntityDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetDiscoveredGroup() []*GroupDTO {
	if m != nil {
		return m.DiscoveredGroup
	}
	return nil
}

func (m *DiscoveryResponse) GetEntityProfile() []*EntityProfileDTO {
	if m != nil {
		return m.EntityProfile
	}
	return nil
}

func (m *DiscoveryResponse) GetDeploymentProfile() []*DeploymentProfileDTO {
	if m != nil {
		return m.DeploymentProfile
	}
	return nil
}

func (m *DiscoveryResponse) GetNotification() []*NotificationDTO {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *DiscoveryResponse) GetMetadataDTO() []*CustomMetadataDTO {
	if m != nil {
		return m.MetadataDTO
	}
	return nil
}

func (m *DiscoveryResponse) GetDerivedTarget() []*DerivedTargetSpecificationDTO {
	if m != nil {
		return m.DerivedTarget
	}
	return nil
}

func (m *DiscoveryResponse) GetNonMarketEntityDTO() []*NonMarketEntityDTO {
	if m != nil {
		return m.NonMarketEntityDTO
	}
	return nil
}

// Custom user-defined account values. These construction is used, when SDK probe writers
// define their own account values, instead of reusing existing ones.
// Custom fields should be used, when there is not predefined field to match the purpose
// of the field required by the probe.
type CustomAccountDefEntry struct {
	// The name of this entry field. The name must be unique for all of the entries you
	// define for this probe.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// The display name of this entry. This is the name that appears in the user interface.
	DisplayName *string `protobuf:"bytes,2,req,name=displayName" json:"displayName,omitempty"`
	// Optional description of what this entry represents.
	Description *string `protobuf:"bytes,3,req,name=description" json:"description,omitempty"`
	// A regular expression to validate a field. If the user's input matches the
	// regular expression, then the entry is valid.
	// For example, you can validate that the entered text is only numbers and period characters
	// for an IP address. To disable validation (allow any text), pass {@code ".*"}.
	VerificationRegex *string `protobuf:"bytes,4,opt,name=verificationRegex,def=.*" json:"verificationRegex,omitempty"`
	// Specifies if the value for the entry can be disclosed (in the log file or wherever else).
	IsSecret *bool `protobuf:"varint,5,opt,name=isSecret,def=0" json:"isSecret,omitempty"`
	// Field type describes, what data type is expected to be put into this field
	//
	// Types that are valid to be assigned to FieldType:
	//	*CustomAccountDefEntry_PrimitiveValue_
	//	*CustomAccountDefEntry_GroupScope
	FieldType        isCustomAccountDefEntry_FieldType `protobuf_oneof:"fieldType"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CustomAccountDefEntry) Reset()                    { *m = CustomAccountDefEntry{} }
func (m *CustomAccountDefEntry) String() string            { return proto1.CompactTextString(m) }
func (*CustomAccountDefEntry) ProtoMessage()               {}
func (*CustomAccountDefEntry) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

const Default_CustomAccountDefEntry_VerificationRegex string = ".*"
const Default_CustomAccountDefEntry_IsSecret bool = false

type isCustomAccountDefEntry_FieldType interface {
	isCustomAccountDefEntry_FieldType()
}

type CustomAccountDefEntry_PrimitiveValue_ struct {
	PrimitiveValue CustomAccountDefEntry_PrimitiveValue `protobuf:"varint,6,opt,name=primitive_value,json=primitiveValue,enum=proto.CustomAccountDefEntry_PrimitiveValue,oneof"`
}
type CustomAccountDefEntry_GroupScope struct {
	GroupScope *CustomAccountDefEntry_GroupScopePropertySet `protobuf:"bytes,7,opt,name=group_scope,json=groupScope,oneof"`
}

func (*CustomAccountDefEntry_PrimitiveValue_) isCustomAccountDefEntry_FieldType() {}
func (*CustomAccountDefEntry_GroupScope) isCustomAccountDefEntry_FieldType()      {}

func (m *CustomAccountDefEntry) GetFieldType() isCustomAccountDefEntry_FieldType {
	if m != nil {
		return m.FieldType
	}
	return nil
}

func (m *CustomAccountDefEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CustomAccountDefEntry) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *CustomAccountDefEntry) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *CustomAccountDefEntry) GetVerificationRegex() string {
	if m != nil && m.VerificationRegex != nil {
		return *m.VerificationRegex
	}
	return Default_CustomAccountDefEntry_VerificationRegex
}

func (m *CustomAccountDefEntry) GetIsSecret() bool {
	if m != nil && m.IsSecret != nil {
		return *m.IsSecret
	}
	return Default_CustomAccountDefEntry_IsSecret
}

func (m *CustomAccountDefEntry) GetPrimitiveValue() CustomAccountDefEntry_PrimitiveValue {
	if x, ok := m.GetFieldType().(*CustomAccountDefEntry_PrimitiveValue_); ok {
		return x.PrimitiveValue
	}
	return CustomAccountDefEntry_STRING
}

func (m *CustomAccountDefEntry) GetGroupScope() *CustomAccountDefEntry_GroupScopePropertySet {
	if x, ok := m.GetFieldType().(*CustomAccountDefEntry_GroupScope); ok {
		return x.GroupScope
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CustomAccountDefEntry) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _CustomAccountDefEntry_OneofMarshaler, _CustomAccountDefEntry_OneofUnmarshaler, _CustomAccountDefEntry_OneofSizer, []interface{}{
		(*CustomAccountDefEntry_PrimitiveValue_)(nil),
		(*CustomAccountDefEntry_GroupScope)(nil),
	}
}

func _CustomAccountDefEntry_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*CustomAccountDefEntry)
	// fieldType
	switch x := m.FieldType.(type) {
	case *CustomAccountDefEntry_PrimitiveValue_:
		b.EncodeVarint(6<<3 | proto1.WireVarint)
		b.EncodeVarint(uint64(x.PrimitiveValue))
	case *CustomAccountDefEntry_GroupScope:
		b.EncodeVarint(7<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.GroupScope); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CustomAccountDefEntry.FieldType has unexpected type %T", x)
	}
	return nil
}

func _CustomAccountDefEntry_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*CustomAccountDefEntry)
	switch tag {
	case 6: // fieldType.primitive_value
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FieldType = &CustomAccountDefEntry_PrimitiveValue_{CustomAccountDefEntry_PrimitiveValue(x)}
		return true, err
	case 7: // fieldType.group_scope
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(CustomAccountDefEntry_GroupScopePropertySet)
		err := b.DecodeMessage(msg)
		m.FieldType = &CustomAccountDefEntry_GroupScope{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CustomAccountDefEntry_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*CustomAccountDefEntry)
	// fieldType
	switch x := m.FieldType.(type) {
	case *CustomAccountDefEntry_PrimitiveValue_:
		n += proto1.SizeVarint(6<<3 | proto1.WireVarint)
		n += proto1.SizeVarint(uint64(x.PrimitiveValue))
	case *CustomAccountDefEntry_GroupScope:
		s := proto1.Size(x.GroupScope)
		n += proto1.SizeVarint(7<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Entity type with a set of properties for group scope account definition
type CustomAccountDefEntry_GroupScopePropertySet struct {
	// Entity type
	EntityType *EntityDTO_EntityType `protobuf:"varint,1,req,name=entityType,enum=proto.EntityDTO_EntityType" json:"entityType,omitempty"`
	// Set of properties
	Property         []*CustomAccountDefEntry_GroupScopeProperty `protobuf:"bytes,2,rep,name=property" json:"property,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) Reset() {
	*m = CustomAccountDefEntry_GroupScopePropertySet{}
}
func (m *CustomAccountDefEntry_GroupScopePropertySet) String() string {
	return proto1.CompactTextString(m)
}
func (*CustomAccountDefEntry_GroupScopePropertySet) ProtoMessage() {}
func (*CustomAccountDefEntry_GroupScopePropertySet) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 0}
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) GetEntityType() EntityDTO_EntityType {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return EntityDTO_SWITCH
}

func (m *CustomAccountDefEntry_GroupScopePropertySet) GetProperty() []*CustomAccountDefEntry_GroupScopeProperty {
	if m != nil {
		return m.Property
	}
	return nil
}

// Entity property for group scope selection
type CustomAccountDefEntry_GroupScopeProperty struct {
	// The name of the property
	PropertyName *string `protobuf:"bytes,1,req,name=propertyName" json:"propertyName,omitempty"`
	// Checks if property is mandatory or optional
	IsMandatory      *bool  `protobuf:"varint,2,opt,name=isMandatory,def=1" json:"isMandatory,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CustomAccountDefEntry_GroupScopeProperty) Reset() {
	*m = CustomAccountDefEntry_GroupScopeProperty{}
}
func (m *CustomAccountDefEntry_GroupScopeProperty) String() string { return proto1.CompactTextString(m) }
func (*CustomAccountDefEntry_GroupScopeProperty) ProtoMessage()    {}
func (*CustomAccountDefEntry_GroupScopeProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 1}
}

const Default_CustomAccountDefEntry_GroupScopeProperty_IsMandatory bool = true

func (m *CustomAccountDefEntry_GroupScopeProperty) GetPropertyName() string {
	if m != nil && m.PropertyName != nil {
		return *m.PropertyName
	}
	return ""
}

func (m *CustomAccountDefEntry_GroupScopeProperty) GetIsMandatory() bool {
	if m != nil && m.IsMandatory != nil {
		return *m.IsMandatory
	}
	return Default_CustomAccountDefEntry_GroupScopeProperty_IsMandatory
}

// The AccountDefinitionEntry class defines a single field that is part of the account credentials
// a user must specify to connect to a target of this probe type. Note that for every probe, the
// 'TARGET_IDENTIFIER' is a mandatory field.
//
// It's the responsibility of your probe to define the credentials it needs to attach to a target. When adding an associated target to
// Operations Manager via the REST API, the API call includes parameters for each of the credentials defined here.
// When attaching via the Operations Manager GUI, the credentials defined here appear in the GUI as individual fields.
// For a given probe, you define the credentials as a Set of AccountDefinitionEntry objects.
type AccountDefEntry struct {
	// Type of account definition
	//
	// Types that are valid to be assigned to Definition:
	//	*AccountDefEntry_PredefinedDefinition
	//	*AccountDefEntry_CustomDefinition
	Definition isAccountDefEntry_Definition `protobuf_oneof:"definition"`
	// Whether this field is mandatory (true) or optional (false). Default is mandatory
	Mandatory *bool `protobuf:"varint,4,opt,name=mandatory,def=1" json:"mandatory,omitempty"`
	// Default value the probe declares for this field. This can only be set if the field is
	// optional.
	DefaultValue     *string `protobuf:"bytes,5,opt,name=defaultValue" json:"defaultValue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountDefEntry) Reset()                    { *m = AccountDefEntry{} }
func (m *AccountDefEntry) String() string            { return proto1.CompactTextString(m) }
func (*AccountDefEntry) ProtoMessage()               {}
func (*AccountDefEntry) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

const Default_AccountDefEntry_Mandatory bool = true

type isAccountDefEntry_Definition interface {
	isAccountDefEntry_Definition()
}

type AccountDefEntry_PredefinedDefinition struct {
	PredefinedDefinition string `protobuf:"bytes,2,opt,name=predefined_definition,json=predefinedDefinition,oneof"`
}
type AccountDefEntry_CustomDefinition struct {
	CustomDefinition *CustomAccountDefEntry `protobuf:"bytes,3,opt,name=custom_definition,json=customDefinition,oneof"`
}

func (*AccountDefEntry_PredefinedDefinition) isAccountDefEntry_Definition() {}
func (*AccountDefEntry_CustomDefinition) isAccountDefEntry_Definition()     {}

func (m *AccountDefEntry) GetDefinition() isAccountDefEntry_Definition {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *AccountDefEntry) GetPredefinedDefinition() string {
	if x, ok := m.GetDefinition().(*AccountDefEntry_PredefinedDefinition); ok {
		return x.PredefinedDefinition
	}
	return ""
}

func (m *AccountDefEntry) GetCustomDefinition() *CustomAccountDefEntry {
	if x, ok := m.GetDefinition().(*AccountDefEntry_CustomDefinition); ok {
		return x.CustomDefinition
	}
	return nil
}

func (m *AccountDefEntry) GetMandatory() bool {
	if m != nil && m.Mandatory != nil {
		return *m.Mandatory
	}
	return Default_AccountDefEntry_Mandatory
}

func (m *AccountDefEntry) GetDefaultValue() string {
	if m != nil && m.DefaultValue != nil {
		return *m.DefaultValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AccountDefEntry) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _AccountDefEntry_OneofMarshaler, _AccountDefEntry_OneofUnmarshaler, _AccountDefEntry_OneofSizer, []interface{}{
		(*AccountDefEntry_PredefinedDefinition)(nil),
		(*AccountDefEntry_CustomDefinition)(nil),
	}
}

func _AccountDefEntry_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*AccountDefEntry)
	// definition
	switch x := m.Definition.(type) {
	case *AccountDefEntry_PredefinedDefinition:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		b.EncodeStringBytes(x.PredefinedDefinition)
	case *AccountDefEntry_CustomDefinition:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.CustomDefinition); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AccountDefEntry.Definition has unexpected type %T", x)
	}
	return nil
}

func _AccountDefEntry_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*AccountDefEntry)
	switch tag {
	case 2: // definition.predefined_definition
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Definition = &AccountDefEntry_PredefinedDefinition{x}
		return true, err
	case 3: // definition.custom_definition
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(CustomAccountDefEntry)
		err := b.DecodeMessage(msg)
		m.Definition = &AccountDefEntry_CustomDefinition{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AccountDefEntry_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*AccountDefEntry)
	// definition
	switch x := m.Definition.(type) {
	case *AccountDefEntry_PredefinedDefinition:
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(len(x.PredefinedDefinition)))
		n += len(x.PredefinedDefinition)
	case *AccountDefEntry_CustomDefinition:
		s := proto1.Size(x.CustomDefinition)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Error DTO. Represent some errors, occurred during operations inside the Mediation Container.
type ErrorDTO struct {
	// Error severity. Used to specify the colour of the message, shown to the end user.
	Severity *ErrorDTO_ErrorSeverity `protobuf:"varint,1,req,name=severity,enum=proto.ErrorDTO_ErrorSeverity" json:"severity,omitempty"`
	// Error description. Should not be null.
	Description *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	// UUID of the entity the error is related to, if any.
	EntityUuid *string `protobuf:"bytes,3,opt,name=entityUuid" json:"entityUuid,omitempty"`
	// Type of the entity the error is related to, if any.
	EntityType       *string `protobuf:"bytes,4,opt,name=entityType" json:"entityType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorDTO) Reset()                    { *m = ErrorDTO{} }
func (m *ErrorDTO) String() string            { return proto1.CompactTextString(m) }
func (*ErrorDTO) ProtoMessage()               {}
func (*ErrorDTO) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *ErrorDTO) GetSeverity() ErrorDTO_ErrorSeverity {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ErrorDTO_CRITICAL
}

func (m *ErrorDTO) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ErrorDTO) GetEntityUuid() string {
	if m != nil && m.EntityUuid != nil {
		return *m.EntityUuid
	}
	return ""
}

func (m *ErrorDTO) GetEntityType() string {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return ""
}

// Custom Metadata DTO.
// Represents custom data that will used by the Operations Manager server for different features.
// Example : for injecting metadata for computing custom pricing for certain commodities.
type CustomMetadataDTO struct {
	// Namespace of the handler for this DTO in the server to handle the metadata
	Namespace *CustomTypeDef_MetadataNamespace `protobuf:"varint,1,req,name=namespace,enum=proto.CustomTypeDef_MetadataNamespace" json:"namespace,omitempty"`
	// Key in the namespace for the data
	Key *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	// Type of data
	DataType *CustomMetadataDTO_Type `protobuf:"varint,3,req,name=dataType,enum=proto.CustomMetadataDTO_Type" json:"dataType,omitempty"`
	// Serializable Data
	Payload          *string `protobuf:"bytes,4,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CustomMetadataDTO) Reset()                    { *m = CustomMetadataDTO{} }
func (m *CustomMetadataDTO) String() string            { return proto1.CompactTextString(m) }
func (*CustomMetadataDTO) ProtoMessage()               {}
func (*CustomMetadataDTO) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *CustomMetadataDTO) GetNamespace() CustomTypeDef_MetadataNamespace {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return CustomTypeDef_UNKNOWN
}

func (m *CustomMetadataDTO) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CustomMetadataDTO) GetDataType() CustomMetadataDTO_Type {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return CustomMetadataDTO_JSON
}

func (m *CustomMetadataDTO) GetPayload() string {
	if m != nil && m.Payload != nil {
		return *m.Payload
	}
	return ""
}

// Structure to hold account parameters, passed to probe to connect and authenticate
// to target.
type AccountValue struct {
	// Name of the parameter. Should refer to the "name" field of AccountDefEntry message,
	// which is returned by the probe in registration phase, for example "userName",
	// "password" and so on.
	Key *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	// String representation of the parameter value, for example "secretpassword",
	// "192.168.111.3" and so on.
	StringValue *string `protobuf:"bytes,2,opt,name=stringValue" json:"stringValue,omitempty"`
	// Set of property value lists
	GroupScopePropertyValues []*AccountValue_PropertyValueList `protobuf:"bytes,3,rep,name=groupScopePropertyValues" json:"groupScopePropertyValues,omitempty"`
	XXX_unrecognized         []byte                            `json:"-"`
}

func (m *AccountValue) Reset()                    { *m = AccountValue{} }
func (m *AccountValue) String() string            { return proto1.CompactTextString(m) }
func (*AccountValue) ProtoMessage()               {}
func (*AccountValue) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *AccountValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AccountValue) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *AccountValue) GetGroupScopePropertyValues() []*AccountValue_PropertyValueList {
	if m != nil {
		return m.GroupScopePropertyValues
	}
	return nil
}

type AccountValue_PropertyValueList struct {
	Value            []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AccountValue_PropertyValueList) Reset()         { *m = AccountValue_PropertyValueList{} }
func (m *AccountValue_PropertyValueList) String() string { return proto1.CompactTextString(m) }
func (*AccountValue_PropertyValueList) ProtoMessage()    {}
func (*AccountValue_PropertyValueList) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6, 0}
}

func (m *AccountValue_PropertyValueList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Use to create (or update) derived targets as a result of certain discovery.
type DerivedTargetSpecificationDTO struct {
	// String identifier to define the type of the probe.
	// If a probe of that type is not registered with the mediation container of current probe,
	// the derived target creation should fail.
	ProbeType *string `protobuf:"bytes,1,req,name=probeType" json:"probeType,omitempty"`
	// Account values provide entry data to the probe.
	// If for any of the keys of these values there is no account definition in the probe registered with probeType,
	// or this set is missing some mandatory account values, the derived target creation should fail.
	// When updating an existing target, all the values that do not constitute target identifier, should be updated.
	AccountValue []*AccountValue `protobuf:"bytes,2,rep,name=accountValue" json:"accountValue,omitempty"`
	// Whether the target should be visible in UI.
	// When an existing target is updated, this should be updated too.
	Hidden *bool `protobuf:"varint,3,opt,name=hidden,def=1" json:"hidden,omitempty"`
	// Whether the target should be created with dependence on the target being discovered.
	// When updating an existing target, it can change from independent to dependent.
	// But not from dependent to independent, or to dependent from another target.
	Dependent        *bool  `protobuf:"varint,4,opt,name=dependent,def=1" json:"dependent,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DerivedTargetSpecificationDTO) Reset()                    { *m = DerivedTargetSpecificationDTO{} }
func (m *DerivedTargetSpecificationDTO) String() string            { return proto1.CompactTextString(m) }
func (*DerivedTargetSpecificationDTO) ProtoMessage()               {}
func (*DerivedTargetSpecificationDTO) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

const Default_DerivedTargetSpecificationDTO_Hidden bool = true
const Default_DerivedTargetSpecificationDTO_Dependent bool = true

func (m *DerivedTargetSpecificationDTO) GetProbeType() string {
	if m != nil && m.ProbeType != nil {
		return *m.ProbeType
	}
	return ""
}

func (m *DerivedTargetSpecificationDTO) GetAccountValue() []*AccountValue {
	if m != nil {
		return m.AccountValue
	}
	return nil
}

func (m *DerivedTargetSpecificationDTO) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return Default_DerivedTargetSpecificationDTO_Hidden
}

func (m *DerivedTargetSpecificationDTO) GetDependent() bool {
	if m != nil && m.Dependent != nil {
		return *m.Dependent
	}
	return Default_DerivedTargetSpecificationDTO_Dependent
}

func init() {
	proto1.RegisterType((*ValidationResponse)(nil), "proto.ValidationResponse")
	proto1.RegisterType((*DiscoveryResponse)(nil), "proto.DiscoveryResponse")
	proto1.RegisterType((*CustomAccountDefEntry)(nil), "proto.CustomAccountDefEntry")
	proto1.RegisterType((*CustomAccountDefEntry_GroupScopePropertySet)(nil), "proto.CustomAccountDefEntry.GroupScopePropertySet")
	proto1.RegisterType((*CustomAccountDefEntry_GroupScopeProperty)(nil), "proto.CustomAccountDefEntry.GroupScopeProperty")
	proto1.RegisterType((*AccountDefEntry)(nil), "proto.AccountDefEntry")
	proto1.RegisterType((*ErrorDTO)(nil), "proto.ErrorDTO")
	proto1.RegisterType((*CustomMetadataDTO)(nil), "proto.CustomMetadataDTO")
	proto1.RegisterType((*AccountValue)(nil), "proto.AccountValue")
	proto1.RegisterType((*AccountValue_PropertyValueList)(nil), "proto.AccountValue.PropertyValueList")
	proto1.RegisterType((*DerivedTargetSpecificationDTO)(nil), "proto.DerivedTargetSpecificationDTO")
	proto1.RegisterEnum("proto.CustomAccountDefEntry_PrimitiveValue", CustomAccountDefEntry_PrimitiveValue_name, CustomAccountDefEntry_PrimitiveValue_value)
	proto1.RegisterEnum("proto.ErrorDTO_ErrorSeverity", ErrorDTO_ErrorSeverity_name, ErrorDTO_ErrorSeverity_value)
	proto1.RegisterEnum("proto.CustomMetadataDTO_Type", CustomMetadataDTO_Type_name, CustomMetadataDTO_Type_value)
}

func init() { proto1.RegisterFile("Discovery.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1078 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xf3, 0xd3, 0xc6, 0x27, 0x69, 0x93, 0x0c, 0x5b, 0xf0, 0x96, 0x2e, 0x04, 0x0b, 0x56,
	0x61, 0x17, 0x19, 0x54, 0x09, 0xd0, 0x16, 0x71, 0xd1, 0x36, 0xd1, 0x36, 0xbb, 0x6d, 0x52, 0x4d,
	0xd2, 0xc2, 0x5d, 0xf1, 0xda, 0x93, 0x30, 0xda, 0xd8, 0x63, 0x8d, 0x27, 0x11, 0x79, 0x1c, 0xde,
	0x82, 0x2b, 0xae, 0x78, 0x00, 0x24, 0x2e, 0x79, 0x04, 0x5e, 0x02, 0xcd, 0xf8, 0x3f, 0x29, 0x95,
	0xd8, 0xab, 0xd8, 0xdf, 0xf7, 0x9d, 0x33, 0x67, 0xce, 0x7c, 0x67, 0x62, 0x68, 0xf5, 0x69, 0xe8,
	0xb0, 0x15, 0xe1, 0x6b, 0x2b, 0xe0, 0x4c, 0x30, 0x54, 0x53, 0x3f, 0x87, 0xad, 0x73, 0xe6, 0x79,
	0xcc, 0xef, 0x4f, 0xc7, 0x11, 0x7e, 0xd8, 0xbe, 0xe6, 0x6c, 0x46, 0x17, 0x24, 0x43, 0x8c, 0x11,
	0xf3, 0xaf, 0x6c, 0xfe, 0x96, 0x88, 0x81, 0x2f, 0xa8, 0x58, 0xa7, 0x8c, 0x79, 0x0a, 0xe8, 0xd6,
	0x5e, 0x50, 0xd7, 0x16, 0x94, 0xf9, 0x98, 0x84, 0x01, 0xf3, 0x43, 0x82, 0x9e, 0x43, 0x9d, 0x70,
	0xce, 0x78, 0x7f, 0x3a, 0x36, 0xb4, 0x6e, 0xa5, 0xd7, 0x38, 0x6e, 0x45, 0x7a, 0x6b, 0x10, 0xc3,
	0x38, 0x15, 0x98, 0x7f, 0x54, 0xa1, 0x93, 0x96, 0xf6, 0x4e, 0x29, 0x90, 0x05, 0x3a, 0x49, 0x0a,
	0x33, 0xca, 0x4a, 0xdd, 0x4e, 0xd4, 0x09, 0x8e, 0x33, 0x09, 0x7a, 0x01, 0x2d, 0x37, 0x5e, 0x91,
	0xb8, 0x2f, 0x39, 0x5b, 0x06, 0x46, 0xa5, 0xb0, 0x86, 0xc2, 0x64, 0xd0, 0xa6, 0x0e, 0x7d, 0x0f,
	0x7b, 0x51, 0x9e, 0xb8, 0x49, 0x46, 0x55, 0x05, 0x7e, 0x50, 0x58, 0x2e, 0x6b, 0x20, 0x2e, 0xaa,
	0xd1, 0x10, 0x3a, 0x2e, 0x09, 0x16, 0x6c, 0xed, 0x11, 0x5f, 0x24, 0x29, 0x6a, 0x2a, 0xc5, 0x87,
	0x71, 0x8a, 0xfe, 0x26, 0x2f, 0xd3, 0x6c, 0x47, 0xa1, 0x13, 0x68, 0xfa, 0x4c, 0xd0, 0x19, 0x75,
	0x54, 0xf3, 0x8d, 0x1d, 0x95, 0xe5, 0xfd, 0x38, 0xcb, 0x28, 0x47, 0xc9, 0x04, 0x05, 0x2d, 0x3a,
	0x81, 0x86, 0x47, 0x84, 0xed, 0xda, 0xc2, 0x96, 0x2d, 0xdb, 0x55, 0xa1, 0x46, 0x1c, 0x7a, 0xbe,
	0x0c, 0x05, 0xf3, 0xae, 0x32, 0x1e, 0xe7, 0xc5, 0xe8, 0x15, 0xec, 0xb9, 0x84, 0xd3, 0x15, 0x71,
	0xa7, 0x36, 0x9f, 0x13, 0x61, 0xd4, 0x55, 0xf4, 0xa7, 0x69, 0xf9, 0x39, 0x6e, 0x12, 0x10, 0xa7,
	0x50, 0x46, 0x31, 0x14, 0x0d, 0x01, 0xf9, 0x5b, 0xd6, 0x32, 0x74, 0x95, 0xf0, 0x71, 0xba, 0x93,
	0x4d, 0x01, 0xbe, 0x27, 0xc8, 0xfc, 0xbd, 0x06, 0x07, 0x51, 0xe5, 0xa7, 0x8e, 0xc3, 0x96, 0xbe,
	0xe8, 0x93, 0xd9, 0xc0, 0x17, 0x7c, 0x8d, 0x10, 0x54, 0x7d, 0xdb, 0x23, 0x86, 0xd6, 0x2d, 0xf7,
	0x74, 0xac, 0x9e, 0x51, 0x17, 0x1a, 0x2e, 0x0d, 0x83, 0x85, 0xbd, 0x1e, 0x49, 0xaa, 0xac, 0xa8,
	0x3c, 0xa4, 0x14, 0x24, 0x74, 0x38, 0x0d, 0x54, 0x77, 0x2b, 0xb1, 0x22, 0x83, 0xd0, 0x57, 0xd0,
	0x59, 0x11, 0x9e, 0x6e, 0x0f, 0x93, 0x39, 0xf9, 0xc5, 0xa8, 0x76, 0xb5, 0x9e, 0x7e, 0x52, 0xb6,
	0x9e, 0xe1, 0x6d, 0x12, 0x7d, 0x02, 0x75, 0x1a, 0x4e, 0x88, 0xc3, 0x89, 0x30, 0x6a, 0x5d, 0xad,
	0x57, 0x3f, 0xa9, 0xcd, 0xec, 0x45, 0x48, 0x70, 0x0a, 0xa3, 0x5b, 0x68, 0x05, 0x9c, 0x7a, 0x54,
	0xd0, 0x15, 0xb9, 0x5b, 0xd9, 0x8b, 0x25, 0x31, 0x76, 0xba, 0x5a, 0x6f, 0xff, 0xf8, 0x79, 0xe1,
	0x74, 0x36, 0xf6, 0x68, 0x5d, 0x27, 0x31, 0xb7, 0x32, 0xe4, 0xa2, 0x84, 0xf7, 0x83, 0x02, 0x82,
	0x6e, 0xa0, 0x31, 0x97, 0x06, 0xbe, 0x0b, 0x1d, 0x16, 0x10, 0x63, 0xb7, 0xab, 0xf5, 0x1a, 0xc7,
	0xc7, 0x0f, 0xe6, 0x54, 0x86, 0x9f, 0x48, 0xf9, 0x35, 0x67, 0x01, 0xe1, 0x62, 0x3d, 0x21, 0xe2,
	0xa2, 0x84, 0x61, 0x9e, 0x12, 0x87, 0xbf, 0x6a, 0x70, 0x70, 0xaf, 0x0e, 0x7d, 0x07, 0x10, 0x59,
	0x7f, 0xba, 0x0e, 0xa2, 0xde, 0xef, 0xa7, 0x16, 0xcf, 0x6e, 0x91, 0x41, 0x2a, 0xc1, 0x39, 0x39,
	0x7a, 0x0d, 0xf5, 0x20, 0xce, 0x15, 0xcf, 0xf3, 0x97, 0xff, 0xb3, 0x54, 0x9c, 0x26, 0x38, 0xfc,
	0x09, 0xd0, 0x36, 0x8f, 0x4c, 0x68, 0x26, 0x8a, 0x51, 0xe6, 0x8e, 0x02, 0x86, 0x9e, 0x42, 0x83,
	0x86, 0x57, 0xb6, 0xef, 0xda, 0x82, 0x71, 0x59, 0x89, 0x3c, 0xb2, 0xaa, 0xe0, 0x4b, 0x82, 0xf3,
	0x84, 0xf9, 0x0d, 0xec, 0x17, 0x0f, 0x00, 0x01, 0xec, 0x4c, 0xa6, 0x78, 0x38, 0x7a, 0xd9, 0xd6,
	0x50, 0x03, 0x76, 0x47, 0x37, 0x57, 0x03, 0x3c, 0x3c, 0x6f, 0x97, 0xe5, 0xcb, 0xd9, 0x78, 0x7c,
	0x39, 0x38, 0x1d, 0xb5, 0x2b, 0x67, 0x0d, 0xd0, 0x67, 0x94, 0x2c, 0x5c, 0xb9, 0x67, 0xf3, 0x1f,
	0x0d, 0x5a, 0x9b, 0xd6, 0xfd, 0x1a, 0x0e, 0x02, 0x4e, 0x5c, 0x32, 0xa3, 0x3e, 0x71, 0xef, 0xd4,
	0x2f, 0x55, 0x76, 0x94, 0xa5, 0xe8, 0x17, 0x25, 0xfc, 0x28, 0xa3, 0xfb, 0x29, 0x8b, 0x5e, 0x43,
	0xc7, 0x51, 0x7d, 0xca, 0x87, 0x54, 0xd4, 0x91, 0x1f, 0x3d, 0xd4, 0xc7, 0x8b, 0x12, 0x6e, 0x47,
	0x81, 0xb9, 0x64, 0x26, 0xe8, 0x5e, 0xda, 0x82, 0x6a, 0xae, 0x05, 0x19, 0x2c, 0x9b, 0xe9, 0x92,
	0x99, 0xbd, 0x5c, 0x08, 0xb5, 0x7d, 0x65, 0x6e, 0x1d, 0x17, 0xb0, 0xb3, 0x26, 0x40, 0x56, 0x8d,
	0xf9, 0x97, 0x06, 0xf5, 0xe4, 0x26, 0x47, 0x2f, 0xa0, 0x1e, 0x12, 0x39, 0x2e, 0x62, 0x1d, 0x3b,
	0xe5, 0xc9, 0xc6, 0x65, 0x1f, 0x3d, 0x4c, 0x62, 0x11, 0x4e, 0xe5, 0x9b, 0x63, 0x5a, 0xde, 0x1e,
	0xd3, 0x8f, 0x12, 0x23, 0xde, 0x2c, 0xa9, 0xab, 0xba, 0xa0, 0xe3, 0x1c, 0x92, 0xf1, 0xca, 0xa8,
	0xd5, 0x3c, 0xaf, 0xce, 0xe5, 0x19, 0xec, 0x15, 0x16, 0x47, 0x4d, 0xa8, 0x9f, 0xe3, 0xe1, 0x74,
	0x78, 0x7e, 0x7a, 0xd9, 0x2e, 0xc9, 0x03, 0xfd, 0xe1, 0x14, 0x8f, 0xd4, 0x51, 0x9b, 0x7f, 0x6b,
	0xd0, 0xd9, 0xba, 0x3e, 0x51, 0x1f, 0x74, 0x79, 0xe9, 0x84, 0x81, 0xed, 0x24, 0x93, 0xf0, 0xb4,
	0x70, 0x0c, 0x72, 0x9d, 0x3e, 0x99, 0x59, 0x49, 0xd0, 0x28, 0x51, 0xe3, 0x2c, 0x10, 0xb5, 0xa1,
	0xf2, 0x96, 0x44, 0x26, 0xd4, 0xb1, 0x7c, 0x94, 0x6d, 0x93, 0x6a, 0x55, 0x77, 0xa5, 0xd0, 0xb6,
	0xad, 0x1a, 0x2c, 0x35, 0x62, 0xa9, 0x1c, 0x19, 0xb0, 0x1b, 0xd8, 0xeb, 0x05, 0xb3, 0x5d, 0xa3,
	0xaa, 0x5a, 0x96, 0xbc, 0x9a, 0x8f, 0xa1, 0xaa, 0x14, 0x75, 0xa8, 0xbe, 0x9a, 0x8c, 0x47, 0xed,
	0x12, 0xda, 0x85, 0xca, 0x8f, 0x57, 0x97, 0x6d, 0xcd, 0xfc, 0x53, 0x83, 0x66, 0xec, 0x98, 0xc8,
	0xe5, 0x71, 0x49, 0xd1, 0xe8, 0xa8, 0x92, 0xba, 0xd0, 0x08, 0x05, 0xa7, 0xfe, 0x3c, 0xf2, 0x41,
	0x54, 0x6c, 0x1e, 0x42, 0x36, 0x18, 0xf3, 0xad, 0x69, 0x54, 0x54, 0x18, 0xff, 0x09, 0x7f, 0x16,
	0x6f, 0x22, 0xbf, 0x94, 0x55, 0x50, 0x5e, 0xd2, 0x50, 0xe0, 0xff, 0x4c, 0x73, 0xf8, 0x39, 0x74,
	0xb6, 0xe4, 0xe8, 0x11, 0xd4, 0xa2, 0xeb, 0x54, 0x7e, 0x4d, 0xe8, 0x38, 0x7a, 0x31, 0x7f, 0xd3,
	0xe0, 0xc9, 0x83, 0xff, 0x58, 0xe8, 0x08, 0xf4, 0x80, 0xb3, 0x37, 0x24, 0xbd, 0xc6, 0x74, 0x9c,
	0x01, 0xe8, 0x5b, 0x68, 0xda, 0xb9, 0x32, 0xe3, 0xcb, 0xea, 0xbd, 0x7b, 0x76, 0x80, 0x0b, 0x42,
	0x74, 0x04, 0x3b, 0x3f, 0x53, 0xd7, 0x25, 0xd1, 0x5c, 0x26, 0x23, 0x15, 0x63, 0x72, 0xe6, 0x5c,
	0x12, 0x10, 0xdf, 0x25, 0xbe, 0x28, 0xce, 0x5c, 0x0a, 0x9f, 0x7d, 0x01, 0x1f, 0x3b, 0xcc, 0xb3,
	0x56, 0x9e, 0x58, 0xf2, 0x37, 0xcc, 0x0a, 0x16, 0xb6, 0x98, 0x31, 0xee, 0x59, 0x8e, 0xfa, 0x9c,
	0xb3, 0x5c, 0xc1, 0xce, 0xf4, 0xf4, 0xbb, 0xea, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x2f,
	0x1c, 0x3f, 0xfe, 0x09, 0x00, 0x00,
}
