// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NonMarketEntityDTO.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// enumerate non market entities
type NonMarketEntityDTO_NonMarketEntityType int32

const (
	NonMarketEntityDTO_CLOUD_SERVICE NonMarketEntityDTO_NonMarketEntityType = 0
	NonMarketEntityDTO_WORKFLOW      NonMarketEntityDTO_NonMarketEntityType = 1
	NonMarketEntityDTO_ACCOUNT       NonMarketEntityDTO_NonMarketEntityType = 2
)

var NonMarketEntityDTO_NonMarketEntityType_name = map[int32]string{
	0: "CLOUD_SERVICE",
	1: "WORKFLOW",
	2: "ACCOUNT",
}
var NonMarketEntityDTO_NonMarketEntityType_value = map[string]int32{
	"CLOUD_SERVICE": 0,
	"WORKFLOW":      1,
	"ACCOUNT":       2,
}

func (x NonMarketEntityDTO_NonMarketEntityType) Enum() *NonMarketEntityDTO_NonMarketEntityType {
	p := new(NonMarketEntityDTO_NonMarketEntityType)
	*p = x
	return p
}
func (x NonMarketEntityDTO_NonMarketEntityType) String() string {
	return proto1.EnumName(NonMarketEntityDTO_NonMarketEntityType_name, int32(x))
}
func (x *NonMarketEntityDTO_NonMarketEntityType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(NonMarketEntityDTO_NonMarketEntityType_value, data, "NonMarketEntityDTO_NonMarketEntityType")
	if err != nil {
		return err
	}
	*x = NonMarketEntityDTO_NonMarketEntityType(value)
	return nil
}
func (NonMarketEntityDTO_NonMarketEntityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

// The NonMarketEntityDTO message represents an Entity discovered in the target that your probe is
// monitoring and this entity does not participate in the market.
//
// Each entity must have a unique ID to identify it in the Operations Manager repository.
// Many targets provide unique IDs for their entities, or you can generate your own.
// To guarantee that it's unique, you can give the ID a prefix that identifies your
// probe and the given target.
//
// Specify entity type by setting a 'NonMarketEntityType' value to the 'entityType' field.
//
// The 'displayName' value appears in the product GUI and in reports to identify the entity.
//
type NonMarketEntityDTO struct {
	EntityType  *NonMarketEntityDTO_NonMarketEntityType `protobuf:"varint,1,req,name=entityType,enum=proto.NonMarketEntityDTO_NonMarketEntityType" json:"entityType,omitempty"`
	Id          *string                                 `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	DisplayName *string                                 `protobuf:"bytes,3,opt,name=displayName" json:"displayName,omitempty"`
	Description *string                                 `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// Collection of entity type's specific data.
	//
	// Types that are valid to be assigned to EntityData:
	//	*NonMarketEntityDTO_CloudServiceData_
	//	*NonMarketEntityDTO_WorkflowData_
	EntityData       isNonMarketEntityDTO_EntityData `protobuf_oneof:"entity_data"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *NonMarketEntityDTO) Reset()                    { *m = NonMarketEntityDTO{} }
func (m *NonMarketEntityDTO) String() string            { return proto1.CompactTextString(m) }
func (*NonMarketEntityDTO) ProtoMessage()               {}
func (*NonMarketEntityDTO) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type isNonMarketEntityDTO_EntityData interface {
	isNonMarketEntityDTO_EntityData()
}

type NonMarketEntityDTO_CloudServiceData_ struct {
	CloudServiceData *NonMarketEntityDTO_CloudServiceData `protobuf:"bytes,500,opt,name=cloud_service_data,json=cloudServiceData,oneof"`
}
type NonMarketEntityDTO_WorkflowData_ struct {
	WorkflowData *NonMarketEntityDTO_WorkflowData `protobuf:"bytes,501,opt,name=workflow_data,json=workflowData,oneof"`
}

func (*NonMarketEntityDTO_CloudServiceData_) isNonMarketEntityDTO_EntityData() {}
func (*NonMarketEntityDTO_WorkflowData_) isNonMarketEntityDTO_EntityData()     {}

func (m *NonMarketEntityDTO) GetEntityData() isNonMarketEntityDTO_EntityData {
	if m != nil {
		return m.EntityData
	}
	return nil
}

func (m *NonMarketEntityDTO) GetEntityType() NonMarketEntityDTO_NonMarketEntityType {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return NonMarketEntityDTO_CLOUD_SERVICE
}

func (m *NonMarketEntityDTO) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *NonMarketEntityDTO) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *NonMarketEntityDTO) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *NonMarketEntityDTO) GetCloudServiceData() *NonMarketEntityDTO_CloudServiceData {
	if x, ok := m.GetEntityData().(*NonMarketEntityDTO_CloudServiceData_); ok {
		return x.CloudServiceData
	}
	return nil
}

func (m *NonMarketEntityDTO) GetWorkflowData() *NonMarketEntityDTO_WorkflowData {
	if x, ok := m.GetEntityData().(*NonMarketEntityDTO_WorkflowData_); ok {
		return x.WorkflowData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NonMarketEntityDTO) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _NonMarketEntityDTO_OneofMarshaler, _NonMarketEntityDTO_OneofUnmarshaler, _NonMarketEntityDTO_OneofSizer, []interface{}{
		(*NonMarketEntityDTO_CloudServiceData_)(nil),
		(*NonMarketEntityDTO_WorkflowData_)(nil),
	}
}

func _NonMarketEntityDTO_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*NonMarketEntityDTO)
	// entity_data
	switch x := m.EntityData.(type) {
	case *NonMarketEntityDTO_CloudServiceData_:
		b.EncodeVarint(500<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.CloudServiceData); err != nil {
			return err
		}
	case *NonMarketEntityDTO_WorkflowData_:
		b.EncodeVarint(501<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.WorkflowData); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NonMarketEntityDTO.EntityData has unexpected type %T", x)
	}
	return nil
}

func _NonMarketEntityDTO_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*NonMarketEntityDTO)
	switch tag {
	case 500: // entity_data.cloud_service_data
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(NonMarketEntityDTO_CloudServiceData)
		err := b.DecodeMessage(msg)
		m.EntityData = &NonMarketEntityDTO_CloudServiceData_{msg}
		return true, err
	case 501: // entity_data.workflow_data
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(NonMarketEntityDTO_WorkflowData)
		err := b.DecodeMessage(msg)
		m.EntityData = &NonMarketEntityDTO_WorkflowData_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NonMarketEntityDTO_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*NonMarketEntityDTO)
	// entity_data
	switch x := m.EntityData.(type) {
	case *NonMarketEntityDTO_CloudServiceData_:
		s := proto1.Size(x.CloudServiceData)
		n += proto1.SizeVarint(500<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *NonMarketEntityDTO_WorkflowData_:
		s := proto1.Size(x.WorkflowData)
		n += proto1.SizeVarint(501<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NonMarketEntityDTO_CloudServiceData struct {
	CloudProvider    *string  `protobuf:"bytes,1,req,name=cloud_provider,json=cloudProvider" json:"cloud_provider,omitempty"`
	Spend            *float32 `protobuf:"fixed32,2,req,name=spend" json:"spend,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NonMarketEntityDTO_CloudServiceData) Reset()         { *m = NonMarketEntityDTO_CloudServiceData{} }
func (m *NonMarketEntityDTO_CloudServiceData) String() string { return proto1.CompactTextString(m) }
func (*NonMarketEntityDTO_CloudServiceData) ProtoMessage()    {}
func (*NonMarketEntityDTO_CloudServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

func (m *NonMarketEntityDTO_CloudServiceData) GetCloudProvider() string {
	if m != nil && m.CloudProvider != nil {
		return *m.CloudProvider
	}
	return ""
}

func (m *NonMarketEntityDTO_CloudServiceData) GetSpend() float32 {
	if m != nil && m.Spend != nil {
		return *m.Spend
	}
	return 0
}

type NonMarketEntityDTO_WorkflowData struct {
	Param            []*NonMarketEntityDTO_Parameter `protobuf:"bytes,1,rep,name=param" json:"param,omitempty"`
	EntityType       *EntityDTO_EntityType           `protobuf:"varint,2,opt,name=entityType,enum=proto.EntityDTO_EntityType" json:"entityType,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *NonMarketEntityDTO_WorkflowData) Reset()         { *m = NonMarketEntityDTO_WorkflowData{} }
func (m *NonMarketEntityDTO_WorkflowData) String() string { return proto1.CompactTextString(m) }
func (*NonMarketEntityDTO_WorkflowData) ProtoMessage()    {}
func (*NonMarketEntityDTO_WorkflowData) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 1}
}

func (m *NonMarketEntityDTO_WorkflowData) GetParam() []*NonMarketEntityDTO_Parameter {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *NonMarketEntityDTO_WorkflowData) GetEntityType() EntityDTO_EntityType {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return EntityDTO_SWITCH
}

type NonMarketEntityDTO_Parameter struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Type             *string `protobuf:"bytes,3,req,name=type,def=String" json:"type,omitempty"`
	Mandatory        *bool   `protobuf:"varint,4,opt,name=mandatory,def=1" json:"mandatory,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NonMarketEntityDTO_Parameter) Reset()                    { *m = NonMarketEntityDTO_Parameter{} }
func (m *NonMarketEntityDTO_Parameter) String() string            { return proto1.CompactTextString(m) }
func (*NonMarketEntityDTO_Parameter) ProtoMessage()               {}
func (*NonMarketEntityDTO_Parameter) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0, 2} }

const Default_NonMarketEntityDTO_Parameter_Type string = "String"
const Default_NonMarketEntityDTO_Parameter_Mandatory bool = true

func (m *NonMarketEntityDTO_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NonMarketEntityDTO_Parameter) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *NonMarketEntityDTO_Parameter) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_NonMarketEntityDTO_Parameter_Type
}

func (m *NonMarketEntityDTO_Parameter) GetMandatory() bool {
	if m != nil && m.Mandatory != nil {
		return *m.Mandatory
	}
	return Default_NonMarketEntityDTO_Parameter_Mandatory
}

func init() {
	proto1.RegisterType((*NonMarketEntityDTO)(nil), "proto.NonMarketEntityDTO")
	proto1.RegisterType((*NonMarketEntityDTO_CloudServiceData)(nil), "proto.NonMarketEntityDTO.CloudServiceData")
	proto1.RegisterType((*NonMarketEntityDTO_WorkflowData)(nil), "proto.NonMarketEntityDTO.WorkflowData")
	proto1.RegisterType((*NonMarketEntityDTO_Parameter)(nil), "proto.NonMarketEntityDTO.Parameter")
	proto1.RegisterEnum("proto.NonMarketEntityDTO_NonMarketEntityType", NonMarketEntityDTO_NonMarketEntityType_name, NonMarketEntityDTO_NonMarketEntityType_value)
}

func init() { proto1.RegisterFile("NonMarketEntityDTO.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xde, 0x16, 0x58, 0xb7, 0xaf, 0x80, 0x75, 0xf4, 0xd0, 0xd4, 0x83, 0x0d, 0x46, 0xd3, 0x98,
	0x58, 0x13, 0x6e, 0xae, 0x27, 0x29, 0x18, 0x8d, 0xbb, 0x74, 0x33, 0xb0, 0x72, 0xf0, 0x40, 0xc6,
	0x76, 0xd6, 0x4c, 0x96, 0x76, 0x9a, 0x61, 0x80, 0x70, 0xf4, 0xe2, 0x9f, 0xe0, 0x5f, 0xaa, 0x77,
	0xd3, 0x99, 0x06, 0x58, 0x7e, 0x9c, 0xda, 0xf7, 0xe5, 0x7d, 0xdf, 0x37, 0x6f, 0xbe, 0x37, 0xe0,
	0x0e, 0x79, 0x7e, 0x4d, 0xc4, 0x3d, 0x95, 0x83, 0x5c, 0x32, 0xb9, 0xee, 0x8f, 0xe3, 0xb0, 0x10,
	0x5c, 0x72, 0xd4, 0x50, 0x1f, 0xef, 0x71, 0xc4, 0xb3, 0x8c, 0xe7, 0x1b, 0xbc, 0xf3, 0xe7, 0x1c,
	0xd0, 0x21, 0x09, 0x5d, 0x03, 0x50, 0x55, 0x8c, 0xd7, 0x05, 0x75, 0x0d, 0xdf, 0x0c, 0xda, 0xdd,
	0xb7, 0x9a, 0x12, 0x1e, 0xf1, 0xd8, 0x83, 0x4a, 0x12, 0xde, 0x11, 0x40, 0x6d, 0x30, 0x59, 0xea,
	0x9a, 0xbe, 0x19, 0x58, 0xd8, 0x64, 0x29, 0xf2, 0xc1, 0x4e, 0xd9, 0xbc, 0x98, 0x91, 0xf5, 0x90,
	0x64, 0xd4, 0xad, 0xf9, 0x46, 0x60, 0xe1, 0x5d, 0x48, 0x75, 0xd0, 0x79, 0x22, 0x58, 0x21, 0x19,
	0xcf, 0xdd, 0x7a, 0xd5, 0xb1, 0x85, 0xd0, 0x77, 0x40, 0xc9, 0x8c, 0x2f, 0xd2, 0xe9, 0x9c, 0x8a,
	0x25, 0x4b, 0xe8, 0x34, 0x25, 0x92, 0xb8, 0x7f, 0x4b, 0x2d, 0xbb, 0xfb, 0xe6, 0xf4, 0x59, 0xa3,
	0x92, 0x34, 0xd2, 0x9c, 0x3e, 0x91, 0xe4, 0xf3, 0x19, 0x76, 0x92, 0x3d, 0x0c, 0x0d, 0xa1, 0xb5,
	0xe2, 0xe2, 0xfe, 0x6e, 0xc6, 0x57, 0x5a, 0xf7, 0x9f, 0xd6, 0x7d, 0x7d, 0x5a, 0x77, 0x52, 0xf5,
	0x57, 0x9a, 0xcd, 0xd5, 0x4e, 0xed, 0xc5, 0xe0, 0xec, 0xfb, 0xa2, 0x57, 0xd0, 0xd6, 0x03, 0x14,
	0x82, 0x2f, 0x59, 0x4a, 0x85, 0xba, 0x67, 0x0b, 0xb7, 0x14, 0x7a, 0x53, 0x81, 0xe8, 0x19, 0x34,
	0xe6, 0x05, 0xcd, 0xf5, 0xf5, 0x99, 0x58, 0x17, 0xde, 0x6f, 0x03, 0x9a, 0xbb, 0x8e, 0xe8, 0x3d,
	0x34, 0x0a, 0x22, 0x48, 0xe6, 0x1a, 0x7e, 0x2d, 0xb0, 0xbb, 0x2f, 0x4f, 0x1f, 0xf4, 0xa6, 0x6c,
	0xa3, 0x92, 0x0a, 0xac, 0x19, 0xe8, 0xc3, 0x83, 0xb0, 0x4d, 0xdf, 0x08, 0xda, 0xdd, 0xe7, 0x15,
	0x7f, 0x4b, 0x3b, 0x1e, 0xad, 0xf7, 0xcb, 0x00, 0x6b, 0xa3, 0x88, 0x10, 0xd4, 0xf3, 0x32, 0x51,
	0x3d, 0x89, 0xfa, 0xdf, 0x8f, 0xd2, 0x3c, 0x8c, 0xd2, 0x83, 0xba, 0x2c, 0xad, 0x6b, 0x25, 0xeb,
	0xf2, 0x7c, 0x24, 0x05, 0xcb, 0x7f, 0x62, 0x85, 0xa1, 0x0e, 0x58, 0x19, 0xc9, 0x53, 0x22, 0xb9,
	0x58, 0xab, 0x35, 0xb8, 0xb8, 0xac, 0x4b, 0xb1, 0xa0, 0x78, 0x0b, 0x77, 0x22, 0x78, 0x7a, 0x64,
	0x03, 0xd1, 0x13, 0x68, 0x45, 0x57, 0xf1, 0x6d, 0x7f, 0x3a, 0x1a, 0xe0, 0x6f, 0x5f, 0xa2, 0x81,
	0x73, 0x86, 0x9a, 0x70, 0x31, 0x89, 0xf1, 0xd7, 0x4f, 0x57, 0xf1, 0xc4, 0x31, 0x90, 0x0d, 0x8f,
	0x3e, 0x46, 0x51, 0x7c, 0x3b, 0x1c, 0x3b, 0x66, 0xaf, 0x05, 0xb6, 0x1e, 0x4b, 0x05, 0xde, 0x7b,
	0x07, 0x2f, 0x12, 0x9e, 0x85, 0xcb, 0x4c, 0x2e, 0xc4, 0x0f, 0x1e, 0x16, 0x33, 0x22, 0xef, 0xb8,
	0xc8, 0xc2, 0x44, 0x3d, 0xa0, 0x30, 0x95, 0xbc, 0xd7, 0xdc, 0x98, 0xf6, 0xc7, 0xf1, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x57, 0xc3, 0x6a, 0x7c, 0x03, 0x00, 0x00,
}
