// Code generated by protoc-gen-go.
// source: PricingDTO.proto
// DO NOT EDIT!

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The unit for the price.
// The unit affects how to use the price to calculate the cost for an entity,
// and is also useful when displaying information for UI purposes.
//
// TODO (roman, Jul 31 2018): Not all units are relevant for all types of cloud entities.
// In the future it may be worth it to have each type of cloud entity have its own unit,
// to avoid confusion.
type Price_Unit int32

const (
	// The price is calculated on an hourly basis.
	// One unit = one hour.
	Price_HOURS Price_Unit = 1
	// The price is calculated on a daily basis.
	// One unit = one day.
	Price_DAYS Price_Unit = 2
	// The price is calculated on a monthly basis.
	// One unit = one month.
	Price_MONTH Price_Unit = 3
	// The price is a total one-time cost.
	Price_TOTAL Price_Unit = 10
	// The price is calculated on a per-IOPS rate.
	// One unit = one million iops.
	Price_MILLION_IOPS Price_Unit = 20
	// The price is calculated on a GB-month.
	// One unit = one GB-month.
	// A GB-month is gigabytes averaged over the month. For example, if you store 30 GB
	// for 15 days of a 30-day month, that would add up to 15 GB-month.
	Price_GB_MONTH Price_Unit = 21
)

var Price_Unit_name = map[int32]string{
	1:  "HOURS",
	2:  "DAYS",
	3:  "MONTH",
	10: "TOTAL",
	20: "MILLION_IOPS",
	21: "GB_MONTH",
}
var Price_Unit_value = map[string]int32{
	"HOURS":        1,
	"DAYS":         2,
	"MONTH":        3,
	"TOTAL":        10,
	"MILLION_IOPS": 20,
	"GB_MONTH":     21,
}

func (x Price_Unit) Enum() *Price_Unit {
	p := new(Price_Unit)
	*p = x
	return p
}
func (x Price_Unit) String() string {
	return proto.EnumName(Price_Unit_name, int32(x))
}
func (x *Price_Unit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Price_Unit_value, data, "Price_Unit")
	if err != nil {
		return err
	}
	*x = Price_Unit(value)
	return nil
}
func (Price_Unit) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{5, 0} }

// The list of prices for a particular compute tier. In the cloud, a compute tier is
// the seller of CPU/memory (but not storage) to a VM. It is commonly referred to as an
// "instance" (e.g. Compute Instance in AWS). We use the tier terminology to be consistent
// across compute and storage, and because you can think of the compute instances as
// different available "tiers" of the Compute service.
//
// A single compute tier may have different available prices depending on other
// configuration option (for example, whether it's shared or a dedicated).
type ComputeTierPriceList struct {
	// The base price is the price of the default - and usually cheapest - configuration.
	// For example, in AWS this would be a shared Linux machine (which has no extra license
	// or tenancy costs).
	BasePrice *ComputeTierPriceList_ComputeTierConfigPrice `protobuf:"bytes,1,opt,name=base_price,json=basePrice" json:"base_price,omitempty"`
	// There are the other configurations available for the tier, and the
	// prices for those configurations ON TOP of the base price. We track it this way
	// so that we can easily separate the compute cost from the license/tenancy cost.
	//
	// For example, if the base price is for a Linux machine that costs $1/hr, and a Windows OS
	// machine costs $1.50/hr, there would be a price adjustment for a Windows OS with price
	// "0.50/hr". To get the full price for a Windows insance you would need to find the
	// appropriate price adjustment, and add it to the base price.
	//
	// The configuration from the base price should not appear in this list.
	PerConfigurationPriceAdjustments []*ComputeTierPriceList_ComputeTierConfigPrice `protobuf:"bytes,2,rep,name=per_configuration_price_adjustments,json=perConfigurationPriceAdjustments" json:"per_configuration_price_adjustments,omitempty"`
	XXX_unrecognized                 []byte                                         `json:"-"`
}

func (m *ComputeTierPriceList) Reset()                    { *m = ComputeTierPriceList{} }
func (m *ComputeTierPriceList) String() string            { return proto.CompactTextString(m) }
func (*ComputeTierPriceList) ProtoMessage()               {}
func (*ComputeTierPriceList) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *ComputeTierPriceList) GetBasePrice() *ComputeTierPriceList_ComputeTierConfigPrice {
	if m != nil {
		return m.BasePrice
	}
	return nil
}

func (m *ComputeTierPriceList) GetPerConfigurationPriceAdjustments() []*ComputeTierPriceList_ComputeTierConfigPrice {
	if m != nil {
		return m.PerConfigurationPriceAdjustments
	}
	return nil
}

// The price for a particular configuration of a compute tier.
type ComputeTierPriceList_ComputeTierConfigPrice struct {
	// The guest operating system.
	GuestOsType *OSType `protobuf:"varint,1,opt,name=guest_os_type,json=guestOsType,enum=common_dto.OSType" json:"guest_os_type,omitempty"`
	// The tenancy for this configuration of the tier.
	// A single tier may have different tenancy options that will be priced differently
	// (e.g. dedicated tenancy is more expensive than shared).
	Tenancy *Tenancy `protobuf:"varint,2,opt,name=tenancy,enum=common_dto.Tenancy" json:"tenancy,omitempty"`
	// The available prices for this configuration of the tier. There may be multiple
	// prices (e.g. an hourly price and a monthly price).
	Prices           []*Price `protobuf:"bytes,10,rep,name=prices" json:"prices,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ComputeTierPriceList_ComputeTierConfigPrice) Reset() {
	*m = ComputeTierPriceList_ComputeTierConfigPrice{}
}
func (m *ComputeTierPriceList_ComputeTierConfigPrice) String() string {
	return proto.CompactTextString(m)
}
func (*ComputeTierPriceList_ComputeTierConfigPrice) ProtoMessage() {}
func (*ComputeTierPriceList_ComputeTierConfigPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{0, 0}
}

func (m *ComputeTierPriceList_ComputeTierConfigPrice) GetGuestOsType() OSType {
	if m != nil && m.GuestOsType != nil {
		return *m.GuestOsType
	}
	return OSType_UNKNOWN_OS
}

func (m *ComputeTierPriceList_ComputeTierConfigPrice) GetTenancy() Tenancy {
	if m != nil && m.Tenancy != nil {
		return *m.Tenancy
	}
	return Tenancy_DEFAULT
}

func (m *ComputeTierPriceList_ComputeTierConfigPrice) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

// The list of prices for a particular database tier. In the cloud, a database tier is
// a managed database solution (e.g. RDS in AWS). It is commonly referred to as an
// "instance" (e.g. Database Instance in AWS). We use the tier terminology to be consistent
// with compute and storage, and because you can think of the database instances as
// different available "tiers" of databases.
//
// A single database tier may have different available prices depending on other
// configuration options (for example, the database engine).
type DatabaseTierPriceList struct {
	// The base price is the price of the default - and usually cheapest - configuration.
	// For example, in AWS this would be a shared Linux machine (which has no extra license
	// or tenancy costs).
	BasePrice *DatabaseTierPriceList_DatabaseTierConfigPrice `protobuf:"bytes,1,opt,name=base_price,json=basePrice" json:"base_price,omitempty"`
	// There are the other configurations available for the database instance, and the
	// prices for those configurations ON TOP of the base price. We track it this way
	// so that we can easily separate the compute cost from the license/tenancy cost.
	//
	// For example, if the base price is for a PostgreSQL machine that costs $1/hr, and an Oracle
	// machine costs $1.50/hr, there would be a price adjustment for Oracle with price
	// "0.50/hr". To get the full price for an Oracle insance you would need to find the
	// appropriate price adjustment, and add it to the base price.
	//
	// The configuration from the base price should not appear in this list.
	ConfigurationPriceAdjustments []*DatabaseTierPriceList_DatabaseTierConfigPrice `protobuf:"bytes,2,rep,name=configuration_price_adjustments,json=configurationPriceAdjustments" json:"configuration_price_adjustments,omitempty"`
	XXX_unrecognized              []byte                                           `json:"-"`
}

func (m *DatabaseTierPriceList) Reset()                    { *m = DatabaseTierPriceList{} }
func (m *DatabaseTierPriceList) String() string            { return proto.CompactTextString(m) }
func (*DatabaseTierPriceList) ProtoMessage()               {}
func (*DatabaseTierPriceList) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *DatabaseTierPriceList) GetBasePrice() *DatabaseTierPriceList_DatabaseTierConfigPrice {
	if m != nil {
		return m.BasePrice
	}
	return nil
}

func (m *DatabaseTierPriceList) GetConfigurationPriceAdjustments() []*DatabaseTierPriceList_DatabaseTierConfigPrice {
	if m != nil {
		return m.ConfigurationPriceAdjustments
	}
	return nil
}

// The price for a particular configuration of a database tier.
type DatabaseTierPriceList_DatabaseTierConfigPrice struct {
	// The database engine to use for this configuration of the tier.
	// Should be set.
	DbEngine *DatabaseEngine `protobuf:"varint,1,opt,name=db_engine,json=dbEngine,enum=common_dto.DatabaseEngine" json:"db_engine,omitempty"`
	// The edition of the engine to use for this configuration of the tier. Not to be confused
	// with "version", which doesn't affect the price.
	//
	// May be unset, because open-source database engines often don't have editions.
	DbEdition *DatabaseEdition `protobuf:"varint,2,opt,name=db_edition,json=dbEdition,enum=common_dto.DatabaseEdition" json:"db_edition,omitempty"`
	// LicenseModel describes all supported license models in cloud projects.
	DbLicenseModel *LicenseModel `protobuf:"varint,3,opt,name=db_license_model,json=dbLicenseModel,enum=common_dto.LicenseModel" json:"db_license_model,omitempty"`
	// // DeploymentType describes all supported deployment types by cloud probes.
	DbDeploymentType *DeploymentType `protobuf:"varint,4,opt,name=db_deployment_type,json=dbDeploymentType,enum=common_dto.DeploymentType" json:"db_deployment_type,omitempty"`
	// The available prices for this configuration of the database tier.
	// There may be different prices (e.g. an hourly price and a monthly price).
	Prices           []*Price `protobuf:"bytes,20,rep,name=prices" json:"prices,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) Reset() {
	*m = DatabaseTierPriceList_DatabaseTierConfigPrice{}
}
func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) String() string {
	return proto.CompactTextString(m)
}
func (*DatabaseTierPriceList_DatabaseTierConfigPrice) ProtoMessage() {}
func (*DatabaseTierPriceList_DatabaseTierConfigPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{1, 0}
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) GetDbEngine() DatabaseEngine {
	if m != nil && m.DbEngine != nil {
		return *m.DbEngine
	}
	return DatabaseEngine_UNKNOWN
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) GetDbEdition() DatabaseEdition {
	if m != nil && m.DbEdition != nil {
		return *m.DbEdition
	}
	return DatabaseEdition_NONE
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) GetDbLicenseModel() LicenseModel {
	if m != nil && m.DbLicenseModel != nil {
		return *m.DbLicenseModel
	}
	return LicenseModel_BRING_YOUR_OWN_LICENSE
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) GetDbDeploymentType() DeploymentType {
	if m != nil && m.DbDeploymentType != nil {
		return *m.DbDeploymentType
	}
	return DeploymentType_SINGLE_AZ
}

func (m *DatabaseTierPriceList_DatabaseTierConfigPrice) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

// The list of prices for a particular IP.
//
// TODO (roman, July 31 2018): It's unclear at the time of this writing what different kinds
// of IPs are available within a region, and whether this model is the best way to represent
// them.
//
// Also, the cost probes currently (July 31 2018) use the same name for all IP Addresses,
// meaning there will only be one IpPriceList per region if we dedupe based on name alone.
//
// However, in AWS there are different IP Address entries within a region. These have different
// group types - charges for IP remaps, charges for IPs attached to a running instance,
// charges for IPs NOT attached to a running instance - represented by different product SKU's.
// Right now the IP Price List is not flexible enough to express all of those options.
type IpPriceList struct {
	// The list of IP prices.
	IpPrice          []*IpPriceList_IpConfigPrice `protobuf:"bytes,1,rep,name=ip_price,json=ipPrice" json:"ip_price,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *IpPriceList) Reset()                    { *m = IpPriceList{} }
func (m *IpPriceList) String() string            { return proto.CompactTextString(m) }
func (*IpPriceList) ProtoMessage()               {}
func (*IpPriceList) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *IpPriceList) GetIpPrice() []*IpPriceList_IpConfigPrice {
	if m != nil {
		return m.IpPrice
	}
	return nil
}

// The price for a particular IP configuration.
type IpPriceList_IpConfigPrice struct {
	// The number of IPs you get for free for an instance.
	// This seems to only be relevant in AWS.
	FreeIpCount *int32 `protobuf:"varint,2,opt,name=free_ip_count,json=freeIpCount" json:"free_ip_count,omitempty"`
	// The prices available for this IP Price. There may be different prices (e.g. an hourly
	// price and a monthly price).
	Prices []*Price `protobuf:"bytes,10,rep,name=prices" json:"prices,omitempty"`
	// Type is used to know if it's a static/ non static.
	Type             *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IpPriceList_IpConfigPrice) Reset()                    { *m = IpPriceList_IpConfigPrice{} }
func (m *IpPriceList_IpConfigPrice) String() string            { return proto.CompactTextString(m) }
func (*IpPriceList_IpConfigPrice) ProtoMessage()               {}
func (*IpPriceList_IpConfigPrice) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2, 0} }

func (m *IpPriceList_IpConfigPrice) GetFreeIpCount() int32 {
	if m != nil && m.FreeIpCount != nil {
		return *m.FreeIpCount
	}
	return 0
}

func (m *IpPriceList_IpConfigPrice) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *IpPriceList_IpConfigPrice) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

// The list of storage prices for a particular cloud storage tier.
type StorageTierPriceList struct {
	// The list of prices.
	//
	// Note: Right now this could be replaced by "repeated Price", but using an extra
	// wrapper is more consistent with the other price lists, and more easily extensible
	// later down the road.
	CloudStoragePrice []*StorageTierPriceList_StorageTierPrice `protobuf:"bytes,1,rep,name=cloud_storage_price,json=cloudStoragePrice" json:"cloud_storage_price,omitempty"`
	XXX_unrecognized  []byte                                   `json:"-"`
}

func (m *StorageTierPriceList) Reset()                    { *m = StorageTierPriceList{} }
func (m *StorageTierPriceList) String() string            { return proto.CompactTextString(m) }
func (*StorageTierPriceList) ProtoMessage()               {}
func (*StorageTierPriceList) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *StorageTierPriceList) GetCloudStoragePrice() []*StorageTierPriceList_StorageTierPrice {
	if m != nil {
		return m.CloudStoragePrice
	}
	return nil
}

type StorageTierPriceList_StorageTierPrice struct {
	Prices           []*Price `protobuf:"bytes,10,rep,name=prices" json:"prices,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StorageTierPriceList_StorageTierPrice) Reset()         { *m = StorageTierPriceList_StorageTierPrice{} }
func (m *StorageTierPriceList_StorageTierPrice) String() string { return proto.CompactTextString(m) }
func (*StorageTierPriceList_StorageTierPrice) ProtoMessage()    {}
func (*StorageTierPriceList_StorageTierPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{3, 0}
}

func (m *StorageTierPriceList_StorageTierPrice) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

// The pricing for reserved instances.
//
// Reserved instances are basically discounted on-demand instances with
// an upfront cost and a term. So instead of paying on-demand, you buy
// "in bulk".
//
// Note: AWS and Azure have reserved instance, and Google has a similar
// concept called "Committed Use Discounts".
type ReservedInstancePrice struct {
	// The total upfront price. May not be set if the payment option for the reserved
	// instance is NO_UPFRONT.
	//
	// TODO (roman, July 31 2019): This may need to be a list, to allow
	// different pricing options. For example, a different hourly vs monthly price.
	UpfrontPrice *Price `protobuf:"bytes,10,opt,name=upfront_price,json=upfrontPrice" json:"upfront_price,omitempty"`
	// The recurring price. This is the amount you have to pay regularly for the instance.
	//
	// TODO (roman, July 31 2019): This may need to be a list, to allow
	// different pricing options. For example, a different hourly vs monthly price.
	RecurringPrice *Price `protobuf:"bytes,11,opt,name=recurring_price,json=recurringPrice" json:"recurring_price,omitempty"`
	// This captures other costs for using the instance - for example, license costs.
	// May not be set, depending on the instance configuration (e.g. a Linux instance
	// will have no license costs).
	//
	// TODO (roman, July 31 2019): This may need to be a list, to allow
	// different pricing options. For example, a different hourly vs monthly price.
	UsagePrice       *Price `protobuf:"bytes,12,opt,name=usage_price,json=usagePrice" json:"usage_price,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReservedInstancePrice) Reset()                    { *m = ReservedInstancePrice{} }
func (m *ReservedInstancePrice) String() string            { return proto.CompactTextString(m) }
func (*ReservedInstancePrice) ProtoMessage()               {}
func (*ReservedInstancePrice) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *ReservedInstancePrice) GetUpfrontPrice() *Price {
	if m != nil {
		return m.UpfrontPrice
	}
	return nil
}

func (m *ReservedInstancePrice) GetRecurringPrice() *Price {
	if m != nil {
		return m.RecurringPrice
	}
	return nil
}

func (m *ReservedInstancePrice) GetUsagePrice() *Price {
	if m != nil {
		return m.UsagePrice
	}
	return nil
}

// The price of a particular instance or cloud entity.
type Price struct {
	// The unit in which the price is measured.
	// Not all units are valid for all types of cloud entities.
	Unit *Price_Unit `protobuf:"varint,1,opt,name=unit,enum=common_dto.Price_Unit" json:"unit,omitempty"`
	// The end range - in units. If not set, assume "infinite".
	// For example, if the price is $0 for the first 10 X, and $10 for the next 10 X, then
	// there should be two Prices, with an end_range of 10 for the first one, and
	// an end_range of 20 for the second. The end is inclusive.
	EndRangeInUnits  *int64          `protobuf:"varint,6,opt,name=end_range_in_units,json=endRangeInUnits" json:"end_range_in_units,omitempty"`
	PriceAmount      *CurrencyAmount `protobuf:"bytes,22,opt,name=price_amount,json=priceAmount" json:"price_amount,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Price) Reset()                    { *m = Price{} }
func (m *Price) String() string            { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()               {}
func (*Price) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *Price) GetUnit() Price_Unit {
	if m != nil && m.Unit != nil {
		return *m.Unit
	}
	return Price_HOURS
}

func (m *Price) GetEndRangeInUnits() int64 {
	if m != nil && m.EndRangeInUnits != nil {
		return *m.EndRangeInUnits
	}
	return 0
}

func (m *Price) GetPriceAmount() *CurrencyAmount {
	if m != nil {
		return m.PriceAmount
	}
	return nil
}

// The prices for license related to a specific operating system
type LicensePriceByOsEntry struct {
	// / The operating system which the license is associated with
	OsType *OSType `protobuf:"varint,1,opt,name=os_type,json=osType,enum=common_dto.OSType" json:"os_type,omitempty"`
	// The list of prices associated with licensing a particular Operating System.
	// Not all cloud providers have license price lists. In particular, Azure does and AWS doesn't.
	// In Azure, license is priced by the number of cores the vm it applies to is using.
	LicensePrices    []*LicensePriceByOsEntry_LicensePrice `protobuf:"bytes,2,rep,name=license_prices,json=licensePrices" json:"license_prices,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *LicensePriceByOsEntry) Reset()                    { *m = LicensePriceByOsEntry{} }
func (m *LicensePriceByOsEntry) String() string            { return proto.CompactTextString(m) }
func (*LicensePriceByOsEntry) ProtoMessage()               {}
func (*LicensePriceByOsEntry) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *LicensePriceByOsEntry) GetOsType() OSType {
	if m != nil && m.OsType != nil {
		return *m.OsType
	}
	return OSType_UNKNOWN_OS
}

func (m *LicensePriceByOsEntry) GetLicensePrices() []*LicensePriceByOsEntry_LicensePrice {
	if m != nil {
		return m.LicensePrices
	}
	return nil
}

type LicensePriceByOsEntry_LicensePrice struct {
	// This is the upper bound of the number of cores this price applies to. E.g. if there are
	// three license prices with pricing for 1-2 cores, 3-4 cores, and 5+ cores, there
	// will be entries with number_of_cores = 2, 4, and MAX_INTEGER.
	NumberOfCores *int32 `protobuf:"varint,1,opt,name=number_of_cores,json=numberOfCores" json:"number_of_cores,omitempty"`
	// The price associated with the number of core and the OS
	Price            *Price `protobuf:"bytes,10,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LicensePriceByOsEntry_LicensePrice) Reset()         { *m = LicensePriceByOsEntry_LicensePrice{} }
func (m *LicensePriceByOsEntry_LicensePrice) String() string { return proto.CompactTextString(m) }
func (*LicensePriceByOsEntry_LicensePrice) ProtoMessage()    {}
func (*LicensePriceByOsEntry_LicensePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{6, 0}
}

func (m *LicensePriceByOsEntry_LicensePrice) GetNumberOfCores() int32 {
	if m != nil && m.NumberOfCores != nil {
		return *m.NumberOfCores
	}
	return 0
}

func (m *LicensePriceByOsEntry_LicensePrice) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

// The price table object contains the pricing information related to a specific cloud provider.
// The cloud provider has pricing for different products and offerings. This means that price for
// different services on the same cloud provider will be all merged together in this object (EC2,
// RDS, ..)
type PriceTable struct {
	// The version of the price table retrieved from the cloud provider.
	// The version can come directly from the cloud provider itself (AWS has a version in its own
	// pricing, like: "version" : "20180809215656")
	// If the cloud provider is not providing a version directly, then the probe needs to generate one
	// on its own.
	// This field will be used by the server side to understand if the price table sent from probe
	// to server is the same one that the server already has. If the version that the server is
	// receiving is the same one that he already processed before, he is free to discard the data.
	Version *string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Information used to uniquely associate this price table with a business account.
	PriceTableKeys []*PricingIdentifier `protobuf:"bytes,8,rep,name=price_table_keys,json=priceTableKeys" json:"price_table_keys,omitempty"`
	// Price table for on-demand instances. this is the "default" pay-per-use option for all cloud
	// providers.
	OnDemandPriceTable []*PriceTable_OnDemandPriceTableByRegionEntry `protobuf:"bytes,2,rep,name=on_demand_price_table,json=onDemandPriceTable" json:"on_demand_price_table,omitempty"`
	SpotPriceTable     []*PriceTable_SpotPriceByRegionEntry          `protobuf:"bytes,4,rep,name=spot_price_table,json=spotPriceTable" json:"spot_price_table,omitempty"`
	// RI price table
	ReservedInstancePriceTable []*PriceTable_ReservedInstancePriceTableByRegionEntry `protobuf:"bytes,5,rep,name=reserved_instance_price_table,json=reservedInstancePriceTable" json:"reserved_instance_price_table,omitempty"`
	// On-Demand License price table by Os type. A table entry represents the list of prices associated
	// with licensing a particular Operating System.
	OnDemandLicensePriceTable []*LicensePriceByOsEntry `protobuf:"bytes,6,rep,name=on_demand_license_price_table,json=onDemandLicensePriceTable" json:"on_demand_license_price_table,omitempty"`
	// Reserved License price table by OS type
	ReservedLicensePriceTable []*LicensePriceByOsEntry `protobuf:"bytes,7,rep,name=reserved_license_price_table,json=reservedLicensePriceTable" json:"reserved_license_price_table,omitempty"`
	XXX_unrecognized          []byte                   `json:"-"`
}

func (m *PriceTable) Reset()                    { *m = PriceTable{} }
func (m *PriceTable) String() string            { return proto.CompactTextString(m) }
func (*PriceTable) ProtoMessage()               {}
func (*PriceTable) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *PriceTable) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *PriceTable) GetPriceTableKeys() []*PricingIdentifier {
	if m != nil {
		return m.PriceTableKeys
	}
	return nil
}

func (m *PriceTable) GetOnDemandPriceTable() []*PriceTable_OnDemandPriceTableByRegionEntry {
	if m != nil {
		return m.OnDemandPriceTable
	}
	return nil
}

func (m *PriceTable) GetSpotPriceTable() []*PriceTable_SpotPriceByRegionEntry {
	if m != nil {
		return m.SpotPriceTable
	}
	return nil
}

func (m *PriceTable) GetReservedInstancePriceTable() []*PriceTable_ReservedInstancePriceTableByRegionEntry {
	if m != nil {
		return m.ReservedInstancePriceTable
	}
	return nil
}

func (m *PriceTable) GetOnDemandLicensePriceTable() []*LicensePriceByOsEntry {
	if m != nil {
		return m.OnDemandLicensePriceTable
	}
	return nil
}

func (m *PriceTable) GetReservedLicensePriceTable() []*LicensePriceByOsEntry {
	if m != nil {
		return m.ReservedLicensePriceTable
	}
	return nil
}

// Spot prices for availability zones in this region
type PriceTable_SpotPriceByRegionEntry struct {
	// Region
	RelatedRegion *EntityDTO `protobuf:"bytes,1,opt,name=related_region,json=relatedRegion" json:"related_region,omitempty"`
	// Availability Zone
	RelatedZone *EntityDTO `protobuf:"bytes,2,opt,name=related_zone,json=relatedZone" json:"related_zone,omitempty"`
	// What Compute Tier
	RelatedComputeTier *EntityDTO `protobuf:"bytes,3,opt,name=related_compute_tier,json=relatedComputeTier" json:"related_compute_tier,omitempty"`
	GuestOsType        *OSType    `protobuf:"varint,4,opt,name=guest_os_type,json=guestOsType,enum=common_dto.OSType" json:"guest_os_type,omitempty"`
	// Spot Price For most recent period
	Price            *Price `protobuf:"bytes,10,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PriceTable_SpotPriceByRegionEntry) Reset()         { *m = PriceTable_SpotPriceByRegionEntry{} }
func (m *PriceTable_SpotPriceByRegionEntry) String() string { return proto.CompactTextString(m) }
func (*PriceTable_SpotPriceByRegionEntry) ProtoMessage()    {}
func (*PriceTable_SpotPriceByRegionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 0}
}

func (m *PriceTable_SpotPriceByRegionEntry) GetRelatedRegion() *EntityDTO {
	if m != nil {
		return m.RelatedRegion
	}
	return nil
}

func (m *PriceTable_SpotPriceByRegionEntry) GetRelatedZone() *EntityDTO {
	if m != nil {
		return m.RelatedZone
	}
	return nil
}

func (m *PriceTable_SpotPriceByRegionEntry) GetRelatedComputeTier() *EntityDTO {
	if m != nil {
		return m.RelatedComputeTier
	}
	return nil
}

func (m *PriceTable_SpotPriceByRegionEntry) GetGuestOsType() OSType {
	if m != nil && m.GuestOsType != nil {
		return *m.GuestOsType
	}
	return OSType_UNKNOWN_OS
}

func (m *PriceTable_SpotPriceByRegionEntry) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

// The on-demand prices in a specific region.
type PriceTable_OnDemandPriceTableByRegionEntry struct {
	// Cloud Region for which those prices are relevant.
	RelatedRegion *EntityDTO `protobuf:"bytes,1,opt,name=related_region,json=relatedRegion" json:"related_region,omitempty"`
	// The prices for compute tiers in this region
	ComputePriceTable []*PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry `protobuf:"bytes,2,rep,name=compute_price_table,json=computePriceTable" json:"compute_price_table,omitempty"`
	// The prices for database tiers in this region
	DatabasePriceTable []*PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry `protobuf:"bytes,3,rep,name=database_price_table,json=databasePriceTable" json:"database_price_table,omitempty"`
	// The prices for cloud storage tiers in this region
	StoragePriceTable []*PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry `protobuf:"bytes,4,rep,name=storage_price_table,json=storagePriceTable" json:"storage_price_table,omitempty"`
	// The prices for IP addresses in this region
	IpPrices         *IpPriceList `protobuf:"bytes,5,opt,name=ip_prices,json=ipPrices" json:"ip_prices,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) Reset() {
	*m = PriceTable_OnDemandPriceTableByRegionEntry{}
}
func (m *PriceTable_OnDemandPriceTableByRegionEntry) String() string {
	return proto.CompactTextString(m)
}
func (*PriceTable_OnDemandPriceTableByRegionEntry) ProtoMessage() {}
func (*PriceTable_OnDemandPriceTableByRegionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 1}
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) GetRelatedRegion() *EntityDTO {
	if m != nil {
		return m.RelatedRegion
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) GetComputePriceTable() []*PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry {
	if m != nil {
		return m.ComputePriceTable
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) GetDatabasePriceTable() []*PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry {
	if m != nil {
		return m.DatabasePriceTable
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) GetStoragePriceTable() []*PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry {
	if m != nil {
		return m.StoragePriceTable
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry) GetIpPrices() *IpPriceList {
	if m != nil {
		return m.IpPrices
	}
	return nil
}

// The prices for compute related to a specific compute tier
type PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry struct {
	// Compute tier for which those prices are relevant.
	RelatedComputeTier   *EntityDTO            `protobuf:"bytes,1,opt,name=related_compute_tier,json=relatedComputeTier" json:"related_compute_tier,omitempty"`
	ComputeTierPriceList *ComputeTierPriceList `protobuf:"bytes,2,opt,name=compute_tier_price_list,json=computeTierPriceList" json:"compute_tier_price_list,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) Reset() {
	*m = PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry{}
}
func (m *PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) String() string {
	return proto.CompactTextString(m)
}
func (*PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) ProtoMessage() {}
func (*PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 1, 0}
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) GetRelatedComputeTier() *EntityDTO {
	if m != nil {
		return m.RelatedComputeTier
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry) GetComputeTierPriceList() *ComputeTierPriceList {
	if m != nil {
		return m.ComputeTierPriceList
	}
	return nil
}

// The prices for database related to a specific database tier
type PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry struct {
	// Database tier for which those prices are relevant.
	RelatedDatabaseTier   *EntityDTO             `protobuf:"bytes,1,opt,name=related_database_tier,json=relatedDatabaseTier" json:"related_database_tier,omitempty"`
	DatabaseTierPriceList *DatabaseTierPriceList `protobuf:"bytes,2,opt,name=database_tier_price_list,json=databaseTierPriceList" json:"database_tier_price_list,omitempty"`
	XXX_unrecognized      []byte                 `json:"-"`
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) Reset() {
	*m = PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry{}
}
func (m *PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) String() string {
	return proto.CompactTextString(m)
}
func (*PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) ProtoMessage() {}
func (*PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 1, 1}
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) GetRelatedDatabaseTier() *EntityDTO {
	if m != nil {
		return m.RelatedDatabaseTier
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry) GetDatabaseTierPriceList() *DatabaseTierPriceList {
	if m != nil {
		return m.DatabaseTierPriceList
	}
	return nil
}

// The prices for storage related to a specific storage tier
type PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry struct {
	// Storage tier for which those prices are relevant.
	RelatedStorageTier   *EntityDTO            `protobuf:"bytes,1,opt,name=related_storage_tier,json=relatedStorageTier" json:"related_storage_tier,omitempty"`
	StorageTierPriceList *StorageTierPriceList `protobuf:"bytes,2,opt,name=storage_tier_price_list,json=storageTierPriceList" json:"storage_tier_price_list,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) Reset() {
	*m = PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry{}
}
func (m *PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) String() string {
	return proto.CompactTextString(m)
}
func (*PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) ProtoMessage() {}
func (*PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 1, 2}
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) GetRelatedStorageTier() *EntityDTO {
	if m != nil {
		return m.RelatedStorageTier
	}
	return nil
}

func (m *PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry) GetStorageTierPriceList() *StorageTierPriceList {
	if m != nil {
		return m.StorageTierPriceList
	}
	return nil
}

// The reserved instance prices in a specific region.
type PriceTable_ReservedInstancePriceTableByRegionEntry struct {
	// Cloud Region for which those prices are relevant.
	RelatedRegion *EntityDTO `protobuf:"bytes,1,opt,name=related_region,json=relatedRegion" json:"related_region,omitempty"`
	// This map contains the RI specs in this region, with its price associated.
	// The RI spec should be considered as a key in a map, so each spec should only be present once
	// in this whole map.
	ReservedInstancePriceMap []*PriceTable_ReservedInstancePriceEntry `protobuf:"bytes,2,rep,name=reserved_instance_price_map,json=reservedInstancePriceMap" json:"reserved_instance_price_map,omitempty"`
	XXX_unrecognized         []byte                                   `json:"-"`
}

func (m *PriceTable_ReservedInstancePriceTableByRegionEntry) Reset() {
	*m = PriceTable_ReservedInstancePriceTableByRegionEntry{}
}
func (m *PriceTable_ReservedInstancePriceTableByRegionEntry) String() string {
	return proto.CompactTextString(m)
}
func (*PriceTable_ReservedInstancePriceTableByRegionEntry) ProtoMessage() {}
func (*PriceTable_ReservedInstancePriceTableByRegionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 2}
}

func (m *PriceTable_ReservedInstancePriceTableByRegionEntry) GetRelatedRegion() *EntityDTO {
	if m != nil {
		return m.RelatedRegion
	}
	return nil
}

func (m *PriceTable_ReservedInstancePriceTableByRegionEntry) GetReservedInstancePriceMap() []*PriceTable_ReservedInstancePriceEntry {
	if m != nil {
		return m.ReservedInstancePriceMap
	}
	return nil
}

// This entry contains an RISpec with the associated price.
type PriceTable_ReservedInstancePriceEntry struct {
	// the RI spec associated with the price
	ReservedInstanceSpec *ReservedInstanceSpec `protobuf:"bytes,1,opt,name=reserved_instance_spec,json=reservedInstanceSpec" json:"reserved_instance_spec,omitempty"`
	// the price of the RI spec
	ReservedInstancePrice *ReservedInstancePrice `protobuf:"bytes,2,opt,name=reserved_instance_price,json=reservedInstancePrice" json:"reserved_instance_price,omitempty"`
	XXX_unrecognized      []byte                 `json:"-"`
}

func (m *PriceTable_ReservedInstancePriceEntry) Reset()         { *m = PriceTable_ReservedInstancePriceEntry{} }
func (m *PriceTable_ReservedInstancePriceEntry) String() string { return proto.CompactTextString(m) }
func (*PriceTable_ReservedInstancePriceEntry) ProtoMessage()    {}
func (*PriceTable_ReservedInstancePriceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor8, []int{7, 3}
}

func (m *PriceTable_ReservedInstancePriceEntry) GetReservedInstanceSpec() *ReservedInstanceSpec {
	if m != nil {
		return m.ReservedInstanceSpec
	}
	return nil
}

func (m *PriceTable_ReservedInstancePriceEntry) GetReservedInstancePrice() *ReservedInstancePrice {
	if m != nil {
		return m.ReservedInstancePrice
	}
	return nil
}

func init() {
	proto.RegisterType((*ComputeTierPriceList)(nil), "common_dto.ComputeTierPriceList")
	proto.RegisterType((*ComputeTierPriceList_ComputeTierConfigPrice)(nil), "common_dto.ComputeTierPriceList.ComputeTierConfigPrice")
	proto.RegisterType((*DatabaseTierPriceList)(nil), "common_dto.DatabaseTierPriceList")
	proto.RegisterType((*DatabaseTierPriceList_DatabaseTierConfigPrice)(nil), "common_dto.DatabaseTierPriceList.DatabaseTierConfigPrice")
	proto.RegisterType((*IpPriceList)(nil), "common_dto.IpPriceList")
	proto.RegisterType((*IpPriceList_IpConfigPrice)(nil), "common_dto.IpPriceList.IpConfigPrice")
	proto.RegisterType((*StorageTierPriceList)(nil), "common_dto.StorageTierPriceList")
	proto.RegisterType((*StorageTierPriceList_StorageTierPrice)(nil), "common_dto.StorageTierPriceList.StorageTierPrice")
	proto.RegisterType((*ReservedInstancePrice)(nil), "common_dto.ReservedInstancePrice")
	proto.RegisterType((*Price)(nil), "common_dto.Price")
	proto.RegisterType((*LicensePriceByOsEntry)(nil), "common_dto.LicensePriceByOsEntry")
	proto.RegisterType((*LicensePriceByOsEntry_LicensePrice)(nil), "common_dto.LicensePriceByOsEntry.LicensePrice")
	proto.RegisterType((*PriceTable)(nil), "common_dto.PriceTable")
	proto.RegisterType((*PriceTable_SpotPriceByRegionEntry)(nil), "common_dto.PriceTable.SpotPriceByRegionEntry")
	proto.RegisterType((*PriceTable_OnDemandPriceTableByRegionEntry)(nil), "common_dto.PriceTable.OnDemandPriceTableByRegionEntry")
	proto.RegisterType((*PriceTable_OnDemandPriceTableByRegionEntry_ComputePriceTableByTierEntry)(nil), "common_dto.PriceTable.OnDemandPriceTableByRegionEntry.ComputePriceTableByTierEntry")
	proto.RegisterType((*PriceTable_OnDemandPriceTableByRegionEntry_DatabasePriceTableByTierEntry)(nil), "common_dto.PriceTable.OnDemandPriceTableByRegionEntry.DatabasePriceTableByTierEntry")
	proto.RegisterType((*PriceTable_OnDemandPriceTableByRegionEntry_StoragePriceTableByTierEntry)(nil), "common_dto.PriceTable.OnDemandPriceTableByRegionEntry.StoragePriceTableByTierEntry")
	proto.RegisterType((*PriceTable_ReservedInstancePriceTableByRegionEntry)(nil), "common_dto.PriceTable.ReservedInstancePriceTableByRegionEntry")
	proto.RegisterType((*PriceTable_ReservedInstancePriceEntry)(nil), "common_dto.PriceTable.ReservedInstancePriceEntry")
	proto.RegisterEnum("common_dto.Price_Unit", Price_Unit_name, Price_Unit_value)
}

func init() { proto.RegisterFile("PricingDTO.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 1425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xd7, 0x26, 0xce, 0xaf, 0x67, 0xc7, 0x71, 0x27, 0x76, 0xe2, 0xef, 0xb6, 0x51, 0x53, 0x7f,
	0x05, 0x2d, 0x54, 0xb5, 0xd4, 0x0a, 0xb5, 0x50, 0x51, 0x44, 0xe2, 0x54, 0xad, 0x45, 0x52, 0x97,
	0xb1, 0xdb, 0xd2, 0x5e, 0x56, 0xeb, 0xdd, 0xb1, 0xb5, 0xd4, 0x9e, 0x5d, 0xcd, 0xcc, 0x56, 0x32,
	0xb7, 0x0a, 0x89, 0xbf, 0x84, 0x13, 0x7f, 0x01, 0xe2, 0x02, 0x12, 0x12, 0x1c, 0x39, 0xf3, 0x17,
	0x70, 0xe7, 0x86, 0xc4, 0x01, 0xed, 0xcc, 0xac, 0xb3, 0x1b, 0xef, 0xc6, 0x49, 0x73, 0xdb, 0x79,
	0xef, 0x7d, 0xde, 0xef, 0x37, 0xf3, 0x16, 0x2a, 0x4f, 0x99, 0xe7, 0x78, 0x74, 0x78, 0xd0, 0xeb,
	0x34, 0x03, 0xe6, 0x0b, 0x1f, 0x81, 0xe3, 0x8f, 0xc7, 0x3e, 0xb5, 0x5c, 0xe1, 0x9b, 0xa8, 0x35,
	0xf2, 0x43, 0xb7, 0xe5, 0x73, 0x31, 0xe5, 0x9b, 0x1b, 0x2d, 0xc9, 0x9f, 0x12, 0x1a, 0xdf, 0x2f,
	0x42, 0xb5, 0xe5, 0x8f, 0x83, 0x50, 0x90, 0x9e, 0x47, 0x58, 0xa4, 0x90, 0x1c, 0x7a, 0x5c, 0xa0,
	0xe7, 0x00, 0x7d, 0x9b, 0x13, 0x2b, 0x88, 0x28, 0x75, 0x63, 0xd7, 0xb8, 0x51, 0xbc, 0x73, 0xaf,
	0x79, 0xac, 0xbe, 0x99, 0x85, 0x4a, 0x12, 0x5b, 0x3e, 0x1d, 0x78, 0x43, 0xc9, 0xc2, 0x6b, 0x91,
	0x2a, 0xf9, 0x89, 0xbe, 0x33, 0xe0, 0xff, 0x01, 0x61, 0x96, 0x23, 0xd9, 0x21, 0xb3, 0x85, 0xe7,
	0x53, 0x65, 0xc5, 0xb2, 0xdd, 0xaf, 0x43, 0x2e, 0xc6, 0x84, 0x0a, 0x5e, 0x5f, 0xd8, 0x5d, 0xbc,
	0x88, 0xc5, 0xdd, 0x20, 0x3e, 0x6b, 0x13, 0x92, 0xbc, 0x77, 0x6c, 0xc0, 0xfc, 0xc1, 0x80, 0xad,
	0x6c, 0x30, 0xba, 0x0b, 0xeb, 0xc3, 0x90, 0x70, 0x61, 0xf9, 0xdc, 0x12, 0x93, 0x40, 0x85, 0x5f,
	0xbe, 0x83, 0x92, 0xce, 0x74, 0xba, 0xbd, 0x49, 0x40, 0x70, 0x51, 0x0a, 0x76, 0x78, 0x74, 0x40,
	0xb7, 0x60, 0x45, 0x10, 0x6a, 0x53, 0x67, 0x52, 0x5f, 0x90, 0x88, 0xcd, 0x24, 0xa2, 0xa7, 0x58,
	0x38, 0x96, 0x41, 0x1f, 0xc0, 0xb2, 0x8c, 0x9b, 0xd7, 0x41, 0x06, 0x7b, 0x29, 0x29, 0xad, 0xc2,
	0xd0, 0x02, 0x8d, 0x9f, 0x0b, 0x50, 0x3b, 0xb0, 0x85, 0x1d, 0xe5, 0x31, 0x5d, 0xa7, 0xaf, 0x32,
	0xea, 0xf4, 0x49, 0x52, 0x51, 0x26, 0x2c, 0x45, 0xcd, 0xa9, 0xd4, 0x5b, 0x03, 0xae, 0x9e, 0xad,
	0x4a, 0x17, 0xb0, 0xb7, 0xe3, 0x9c, 0x5a, 0xa4, 0xdf, 0x17, 0x60, 0x3b, 0x07, 0x8a, 0xee, 0xc1,
	0x9a, 0xdb, 0xb7, 0x08, 0x1d, 0x7a, 0x34, 0xae, 0x90, 0x99, 0xe5, 0xc8, 0x43, 0x29, 0x81, 0x57,
	0xdd, 0xbe, 0xfa, 0x42, 0xf7, 0x01, 0x22, 0xa0, 0xeb, 0x45, 0x26, 0x75, 0xa5, 0x2e, 0x67, 0x22,
	0x95, 0x08, 0x5e, 0x73, 0xfb, 0xfa, 0x13, 0xed, 0x43, 0xc5, 0xed, 0x5b, 0x23, 0xcf, 0x21, 0x94,
	0x13, 0x6b, 0xec, 0xbb, 0x64, 0x54, 0x5f, 0x94, 0x1a, 0xea, 0x49, 0x0d, 0x87, 0x4a, 0xe0, 0x28,
	0xe2, 0xe3, 0xb2, 0xdb, 0x4f, 0x9e, 0xd1, 0x63, 0x40, 0x6e, 0xdf, 0x72, 0x49, 0x30, 0xf2, 0x27,
	0x51, 0x98, 0xaa, 0xc7, 0x0a, 0x19, 0x11, 0x4c, 0x45, 0x64, 0xaf, 0x55, 0xdc, 0x7e, 0x9a, 0x92,
	0xe8, 0xa0, 0xea, 0xbc, 0x0e, 0xfa, 0xd5, 0x80, 0x62, 0x3b, 0x38, 0xee, 0x9b, 0xcf, 0x61, 0xd5,
	0x0b, 0xa6, 0x5d, 0x13, 0x81, 0xdf, 0x4b, 0x82, 0x13, 0xa2, 0xcd, 0x76, 0x90, 0xac, 0xd8, 0x8a,
	0xa7, 0x58, 0x26, 0x83, 0xf5, 0x14, 0x07, 0x35, 0x60, 0x7d, 0xc0, 0x08, 0xb1, 0xbc, 0xc0, 0x72,
	0xfc, 0x90, 0x0a, 0x99, 0xda, 0x25, 0x5c, 0x8c, 0x88, 0x91, 0x64, 0x48, 0xc5, 0x39, 0x7a, 0x1e,
	0x21, 0x28, 0x4c, 0x87, 0x6f, 0x0d, 0xcb, 0xef, 0xc6, 0x8f, 0x06, 0x54, 0xbb, 0xc2, 0x67, 0xf6,
	0xf0, 0xc4, 0x18, 0xd8, 0xb0, 0xe9, 0x44, 0xd7, 0x9d, 0xc5, 0x15, 0x37, 0x15, 0xd9, 0xed, 0xa4,
	0x91, 0x2c, 0xf8, 0x0c, 0x11, 0x5f, 0x92, 0xda, 0x34, 0x59, 0xc5, 0xfb, 0x00, 0x2a, 0x27, 0xc5,
	0xce, 0x35, 0xc2, 0x06, 0xd4, 0x30, 0xe1, 0x84, 0xbd, 0x21, 0x6e, 0x9b, 0x72, 0x61, 0x53, 0x87,
	0x4c, 0xaf, 0x9b, 0x30, 0x18, 0x30, 0x9f, 0x0a, 0xed, 0x35, 0xc8, 0x29, 0xce, 0xd0, 0x55, 0xd2,
	0x72, 0x0a, 0x77, 0x1f, 0x36, 0x18, 0x71, 0x42, 0xc6, 0x3c, 0x3a, 0xd4, 0xc8, 0x62, 0x1e, 0xb2,
	0x3c, 0x95, 0x54, 0xd8, 0x3b, 0x50, 0x0c, 0xf9, 0x71, 0x9e, 0x4a, 0x79, 0x38, 0x90, 0x52, 0xf2,
	0xbb, 0xf1, 0xb7, 0x01, 0x4b, 0x0a, 0xfd, 0x21, 0x14, 0x42, 0xea, 0x09, 0x3d, 0x75, 0x5b, 0x33,
	0xb0, 0xe6, 0x33, 0xea, 0x09, 0x2c, 0x65, 0xd0, 0x4d, 0x40, 0x84, 0xba, 0x16, 0xb3, 0xe9, 0x90,
	0x58, 0x1e, 0xb5, 0x22, 0x22, 0xaf, 0x2f, 0xef, 0x1a, 0x37, 0x16, 0xf1, 0x06, 0xa1, 0x2e, 0x8e,
	0x18, 0x6d, 0x1a, 0x21, 0x38, 0x7a, 0x00, 0x25, 0x7d, 0xc9, 0x8c, 0x65, 0x07, 0x6d, 0x49, 0xbf,
	0x52, 0x43, 0xd1, 0x0a, 0x19, 0x23, 0xd4, 0x99, 0xec, 0x49, 0x09, 0x5c, 0x94, 0xf2, 0xea, 0xd0,
	0xf8, 0x12, 0x0a, 0x91, 0x1e, 0xb4, 0x06, 0x4b, 0x8f, 0x3b, 0xcf, 0x70, 0xb7, 0x62, 0xa0, 0x55,
	0x28, 0x1c, 0xec, 0xbd, 0xec, 0x56, 0x16, 0x22, 0xe2, 0x51, 0xe7, 0x49, 0xef, 0x71, 0x65, 0x31,
	0xfa, 0xec, 0x75, 0x7a, 0x7b, 0x87, 0x15, 0x40, 0x15, 0x28, 0x1d, 0xb5, 0x0f, 0x0f, 0xdb, 0x9d,
	0x27, 0x56, 0xbb, 0xf3, 0xb4, 0x5b, 0xa9, 0xa2, 0x12, 0xac, 0x3e, 0xda, 0xb7, 0x94, 0x68, 0xad,
	0xf1, 0xaf, 0x01, 0x35, 0x3d, 0xbd, 0x32, 0xb4, 0xfd, 0x49, 0x87, 0x3f, 0xa4, 0x82, 0x4d, 0xd0,
	0x4d, 0x58, 0x99, 0xff, 0x3e, 0x2c, 0xfb, 0xea, 0x69, 0x78, 0x06, 0xe5, 0xf8, 0xd2, 0xd0, 0x0d,
	0xa3, 0xae, 0xce, 0x66, 0xc6, 0xad, 0x91, 0xb6, 0x93, 0xa2, 0xe2, 0xf5, 0x51, 0xe2, 0xc4, 0x4d,
	0x0b, 0x4a, 0x49, 0x36, 0x7a, 0x1f, 0x36, 0x68, 0x38, 0xee, 0x13, 0x66, 0xf9, 0x03, 0xcb, 0xf1,
	0x19, 0xe1, 0xd2, 0xb7, 0x25, 0xbc, 0xae, 0xc8, 0x9d, 0x41, 0x2b, 0x22, 0xa2, 0xeb, 0xb0, 0x34,
	0xa7, 0xd5, 0x14, 0xbf, 0xf1, 0xd7, 0x26, 0x80, 0x24, 0xf4, 0xec, 0xfe, 0x88, 0xa0, 0x3a, 0xac,
	0xbc, 0x21, 0x8c, 0x47, 0xf7, 0xa6, 0x1a, 0xcb, 0xf8, 0x88, 0x1e, 0x41, 0x45, 0x55, 0x4e, 0x44,
	0x82, 0xd6, 0x6b, 0x32, 0xe1, 0xf5, 0x55, 0x19, 0xe2, 0xce, 0x49, 0xe5, 0x1e, 0x1d, 0xb6, 0x5d,
	0x42, 0x85, 0x37, 0xf0, 0x08, 0xc3, 0xe5, 0x60, 0xaa, 0xfe, 0x0b, 0x32, 0xe1, 0xc8, 0x83, 0x5a,
	0x24, 0x4b, 0xc6, 0x36, 0x75, 0xad, 0x84, 0x4a, 0x9d, 0xb0, 0xbb, 0x33, 0xae, 0x4a, 0x68, 0xb3,
	0x43, 0x0f, 0x24, 0xe4, 0x98, 0xb4, 0x3f, 0xc1, 0x64, 0xe8, 0xf9, 0x54, 0x66, 0x11, 0x23, 0x7f,
	0x46, 0x00, 0xbd, 0x80, 0x0a, 0x0f, 0x7c, 0x91, 0xb2, 0x52, 0x90, 0x56, 0x6e, 0xe5, 0x58, 0xe9,
	0x06, 0xbe, 0xd0, 0xe5, 0x49, 0x2a, 0x2f, 0xf3, 0x98, 0xae, 0x14, 0xbf, 0x35, 0x60, 0x87, 0xe9,
	0x59, 0xb7, 0x3c, 0x3d, 0xec, 0x29, 0x33, 0x4b, 0xd2, 0xcc, 0x67, 0x39, 0x66, 0x32, 0xef, 0x89,
	0x8c, 0xa0, 0x4c, 0x96, 0x2b, 0x88, 0x1c, 0xd8, 0x39, 0xce, 0x63, 0xaa, 0xf7, 0xb4, 0x0b, 0xcb,
	0xd2, 0x85, 0x6b, 0x73, 0x1b, 0x10, 0xff, 0x2f, 0x4e, 0x5d, 0x92, 0xad, 0x8c, 0xf4, 0xe1, 0xca,
	0x34, 0xce, 0x2c, 0x1b, 0x2b, 0x67, 0xb6, 0x11, 0xab, 0x99, 0xb1, 0x61, 0xfe, 0xb4, 0x00, 0x5b,
	0xd9, 0x79, 0x47, 0x9f, 0x42, 0x99, 0x91, 0x91, 0x2d, 0x88, 0x6b, 0x31, 0x49, 0xd6, 0x0b, 0x50,
	0x2d, 0x69, 0xf0, 0x21, 0x15, 0x9e, 0x98, 0x1c, 0xf4, 0x3a, 0x78, 0x5d, 0x0b, 0x2b, 0x15, 0xe8,
	0x63, 0x28, 0xc5, 0xe8, 0x6f, 0x7c, 0x4a, 0xe4, 0x73, 0x95, 0x8b, 0x2d, 0x6a, 0xd1, 0x57, 0x3e,
	0x25, 0xe8, 0x11, 0x54, 0x63, 0xa4, 0xa3, 0x56, 0x48, 0x4b, 0x78, 0x84, 0xc9, 0x4d, 0x20, 0x57,
	0x03, 0xd2, 0x90, 0xc4, 0xd2, 0x39, 0xbb, 0x69, 0x16, 0xce, 0xb6, 0x69, 0x9e, 0x75, 0x7e, 0xcd,
	0x7f, 0x56, 0xe1, 0xea, 0x9c, 0xd1, 0xb8, 0x60, 0x16, 0xbf, 0x35, 0x60, 0x33, 0x4e, 0xc2, 0xec,
	0xb8, 0x76, 0xdf, 0x6d, 0x5c, 0xe3, 0xb5, 0x3e, 0xc9, 0x8e, 0x12, 0xa6, 0x9a, 0xe5, 0x92, 0x73,
	0x92, 0x1b, 0xfd, 0x56, 0x54, 0x5d, 0xbd, 0xb6, 0xa5, 0xdc, 0x58, 0x94, 0x6e, 0xf4, 0xde, 0xd1,
	0x8d, 0x78, 0x13, 0xcc, 0xf6, 0x03, 0xb9, 0x33, 0x6c, 0x99, 0x8e, 0xd4, 0x0e, 0x92, 0xba, 0x57,
	0xde, 0x35, 0x1d, 0xc9, 0x45, 0x64, 0x36, 0x1d, 0xfc, 0x24, 0x17, 0x7d, 0x04, 0x6b, 0xf1, 0x76,
	0xc7, 0xeb, 0x4b, 0xb2, 0x9a, 0xdb, 0x39, 0xeb, 0x1d, 0x5e, 0xd5, 0x0b, 0x1d, 0x37, 0x7f, 0x31,
	0xe0, 0xca, 0x69, 0x89, 0xcf, 0xed, 0x7b, 0xe3, 0xbc, 0x7d, 0xff, 0x02, 0xb6, 0x93, 0x0a, 0x74,
	0xa6, 0x46, 0x1e, 0x17, 0x7a, 0x0a, 0x77, 0xe7, 0xfd, 0xf8, 0xe1, 0xaa, 0x93, 0x41, 0x35, 0x7f,
	0x33, 0x60, 0xe7, 0xd4, 0xa2, 0xa1, 0x36, 0xd4, 0xe2, 0x18, 0xa6, 0x0d, 0x33, 0x3f, 0x88, 0x4d,
	0x8d, 0x49, 0xfe, 0x8c, 0xa0, 0x57, 0x50, 0x4f, 0xa9, 0x98, 0x0d, 0xe3, 0xda, 0xdc, 0x3f, 0x23,
	0x5c, 0x73, 0xb3, 0xc8, 0xb2, 0x16, 0xa7, 0x55, 0x3d, 0x59, 0x8b, 0xb8, 0xdf, 0xce, 0x5e, 0x8b,
	0xc4, 0x22, 0x1b, 0xd5, 0x22, 0xa9, 0x60, 0x4e, 0x2d, 0xb2, 0xd6, 0x67, 0x5c, 0xe5, 0x19, 0x54,
	0xf3, 0x4f, 0x03, 0xae, 0x9f, 0xf1, 0x25, 0xbb, 0xe0, 0x1d, 0x14, 0xc0, 0xe5, 0xbc, 0xe7, 0x76,
	0x6c, 0x07, 0xfa, 0x2a, 0xba, 0x7d, 0x9e, 0xc7, 0x56, 0x4d, 0x56, 0x3d, 0xf3, 0x7d, 0x3d, 0xb2,
	0x03, 0xf3, 0x0f, 0x03, 0xcc, 0x7c, 0x20, 0x7a, 0x0e, 0x5b, 0xb3, 0x0e, 0xf1, 0x80, 0x38, 0x3a,
	0xac, 0x54, 0x4a, 0x4f, 0xea, 0xe9, 0x06, 0xc4, 0xc1, 0x55, 0x96, 0x41, 0x45, 0x2f, 0x61, 0x3b,
	0x27, 0xd0, 0xac, 0x86, 0xcb, 0x74, 0x10, 0xd7, 0x32, 0x83, 0xda, 0xbf, 0x16, 0xfd, 0xed, 0x8f,
	0x9b, 0x6f, 0xc6, 0x22, 0x64, 0x7d, 0xbf, 0x19, 0x8c, 0x6c, 0x31, 0xf0, 0xd9, 0xb8, 0xc9, 0xdd,
	0xd7, 0x5a, 0xe7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0x41, 0x93, 0xd3, 0x70, 0x12, 0x00,
	0x00,
}
